Xliff merge tool
uyuni-project/uyuni pull request #2525
Opened 2020-08-26 11:12 UTC by admd

## What does this PR change?

A simple tool to manage xliff files

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +        item.set('state', 'new')
`state` is an attribute for "&lt;target&gt;". Here it seems you set it on &lt;trans-unit&gt; .
But I think we do not need to set state=new as a missing &lt;target&gt; has the same effect

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +        trans_unit.set('state', 'needs-adaptation')
`state` is an attribute for "&lt;target&gt;". Here it seems you set it on &lt;trans-unit&gt;

http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +        trans_unit[0].text = id_new_value_dict[trans_unit.attrib['id']]
Can we be sure that trans_unit[0] is element "source"? I think we better pick the source element explicit.

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +        org_trans_units_sources = {tr_unit.attrib['id']: tr_unit[0].text for tr_unit in original_trans_units}
Can we be sure that tr_unit[0] is element "source"? I think we better pick the source element explicit.

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +
What about `else:` (if len(translation_trans_units) == len(original_trans_units):)

I think we should at least write a message

2020-08-26 14:54 UTC, mcalmer commented on scripts/translation/xliffmerger.py
> +files = os.listdir('.')
Would be good if we could provide the working directory as command line parameter.

2020-08-28 15:38 UTC, admd commented
@mcalmer 
`xliffmerge` tool is ready to test. I have added another small script `trans-units-extractor` script to extract `trans-units` from `<group>` element and then remove that parent `<group>` element. It works but doesn't keep the order which makes diff pretty bad. I will try to see if we can somehow keep the order.

2020-08-28 17:59 UTC, mcalmer commented
@parlt91 will take over now.

2020-08-31 11:57 UTC, admd commented
The order has been fixed. Now the only thing which is kinda bad is that during modifying, our tools remove the comments if there are any in that translation file. I will be looking into hacking around this part and see if somehow we can keep the comments while using the standard python library. There are some third parties libraries that take care of comments as well but I would prefer to stick with the standard library for the time being.

2020-08-31 11:58 UTC, admd commented
Pascal if you get some free time, it would be cool if you could play with these 2 small scripts. Let me know if you need any information. @parlt91

2020-08-31 13:15 UTC, parlt91 commented
@admd Sure. I should have some time to check them out tomorrow.

2020-09-01 15:11 UTC, parlt91 commented
@admd So, I played around with the scripts a bit.
I could not find any issues with adding, removing or updating the strings.

I really like adding the `new` and `needs-adaptation` flags :+1: 
I wonder if we could add the`new` flag to all strings that still lack translation? (they should be missing the `<target>` in this case)

2020-09-03 09:12 UTC, admd commented
Thank you @parlt91 for having a look. 

> I wonder if we could add the`new` flag to all strings that still lack translation? (they should be missing the `<target>` in this case)
It was based on the assumption that weblate takes care of it, if <target> element is missing, weblate automatically assumes that this needs translation. Ofcourse, I could be wrong as I haven't tested and in that case, we will need to add the element as you suggested. 

BTW I have added a commit and now hopefully comments will be kept and not removed.

2020-09-04 12:33 UTC, parlt91 requested changes
Overall looks already pretty good.
Preserving the comments seems to work fine.
The known issues of messing with the indentation and the order of the translations still persist, but they don't break functionality, so I could personally life with that.

2020-09-04 12:33 UTC, parlt91 commented on scripts/translation/xliffmerger.py
> +args = parser.parse_args()
`parser` -> `argparser`

2020-09-04 12:33 UTC, parlt91 commented on scripts/translation/xliffmerger.py
> +    parser = ET.XMLParser(target=CommentedTreeBuilder())
Using the same instance of `parser` two parse both files does not seem to work for me

```
INFO:root:
processing StringResource_ca.xml
Traceback (most recent call last):
  File "/home/pascal/git/uyuni/scripts/translation/xliffmerger.py", line 123, in <module>
    process(original, translation)
  File "/home/pascal/git/uyuni/scripts/translation/xliffmerger.py", line 53, in process
    xml_tree_original = ET.parse(original_file, parser=parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 603, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: parsing finished: line 23921, column 8
```

2020-09-04 12:33 UTC, parlt91 commented on scripts/translation/xliffmerger.py
> +    parser = ET.XMLParser(target=CommentedTreeBuilder())
Creating two parsers seems to work
```
parser1 = ET.XMLParser(target=CommentedTreeBuilder())
parser2 = ET.XMLParser(target=CommentedTreeBuilder())
xml_tree_original = ET.parse(original_file, parser=parser1)
xml_tree_translation = ET.parse(translation_file, parser=parser2)
```
I have no idea why though

2020-09-04 12:33 UTC, parlt91 commented on scripts/translation/xliffmerger.py
> +    #xml_tree_translation.write(translation, encoding='utf-8', xml_declaration=True)
Should be un-commented before merging

2020-09-04 12:33 UTC, parlt91 commented on scripts/translation/xliffmerger.py
> +    # body_element = root_node[0][0]
Also make sure to remove unneeded comments

2020-09-07 10:09 UTC, admd commented
Hey Pascal, thank you for the review. There were quite a few facepalms :), this is what happens with last-minute changes. I have made the suggested changes. @parlt91

2020-09-07 10:32 UTC, parlt91 approved these changes
LGTM now. Thank you :+1:

2020-09-07 10:48 UTC, merged