WIP: rework filelocking used for scc sync
uyuni-project/uyuni pull request #2580
Opened 2020-09-08 14:22 UTC by lucidd

## What does this PR change?

This PR reworks the file locking we use for synchronize scc refresh between tomcat and taskomatic in an effort to simplify the code and usage. There also have been some issues indicating that the current locking may not always work but since this issue has not been reproduced so far its unclear if the new code resolves this.

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed

- [ ] **DONE**

## Test coverage
- No tests

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2020-09-08 15:12 UTC, mcalmer requested changes
Just small issues in doc and checkstyle is also not green. But the code looks good.
Not sure if there was a bug to name it in the changelog. If not you can also click the "no changelog" checkbox

2020-09-08 15:12 UTC, mcalmer commented on java/code/src/com/redhat/rhn/common/util/FileLocks.java
> + * Copyright (c) 2018 SUSE LLC
old copyright year

2020-09-08 15:12 UTC, mcalmer commented on java/code/src/com/redhat/rhn/common/util/FileLocks.java
> + * SCCRefreshLock - locks the SCC refresh process
old comment from former class name

2020-09-08 15:12 UTC, mcalmer commented on java/code/src/com/redhat/rhn/common/util/FileLocks.java
> +    public static FileLocks SCC_REFRESH_LOCK =
As it is public, does it need a comment?

2020-09-08 15:48 UTC, lucidd commented
> Not sure if there was a bug to name it in the changelog. If not you can also click the "no changelog" checkbox

There is potentially a bug related to this but its not confirmed yet that the locking is the issue and if this PR fixes it. I will leave this PR open until we have more information.

2020-10-15 10:42 UTC, mcalmer approved these changes

2020-11-12 10:53 UTC, merged