Added RHEL8 support
uyuni-project/uyuni pull request #2816
Opened 2020-11-08 20:13 UTC by sbluhm

## What does this PR change?

Added RHEL8 build support.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: No functionality change

- [X] **DONE**

## Test coverage
- No tests: No code change

- [X] **DONE**

## Links

Fixes #
None

- [X] **DONE**

## Changelogs
- Added RHEL8 support

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_lint_checkstyle"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2020-11-14 13:12 UTC, mcalmer requested changes
I added one suggestion to prevent using sed.

Please also add a line in web/spacewalk-web.changes .
Please do not add a Header. Just one line on top of the file with what you changed.

The Header is added later automatically when we submit for uyuni.

2020-11-14 13:12 UTC, mcalmer commented on web/spacewalk-web.spec
>  make -C html install PREFIX=$RPM_BUILD_ROOT
```suggestion
make -C html install PREFIX=$RPM_BUILD_ROOT INSTALL_DEST=%{www_path}/www/htdocs
```

2020-11-14 13:18 UTC, mcalmer commented
@sbluhm About changelogs https://github.com/uyuni-project/uyuni/wiki/Contributing#git-changelogs

2020-11-14 14:54 UTC, sbluhm commented
Thank you. Added your feedback.

2020-11-15 10:07 UTC, mcalmer approved these changes
Looks good to me. Thanks.

2020-11-15 10:07 UTC, merged