disable password validation on user creation with empty password and pam enabled. (bsc#1179579)
uyuni-project/uyuni pull request #2992
Opened 2020-12-09 14:01 UTC by lucidd

## What does this PR change?

This fixes an issue when creating a user with pam authentication where no password is provided. In this case there will be a dummy password generated to get though struts from validation. Later There is again validation checking the password against the configured requirements. This validation can fail since the dummy password is a constant length hash that won't always fit the configured requirements. This fix disabled the seconds password requirements validation for said dummy password but keeps it in place for all other cases.

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed

- [ ] **DONE**

## Test coverage
- No tests

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2020-12-09 14:43 UTC, mcalmer requested changes
In addition to the changelog there are 2 checkstyle issues

2020-12-09 14:43 UTC, mcalmer commented on java/spacewalk-java.changes
> +- Fix user creation with pam auth and no password (bsc#1179579)
Julio do not like it when the new message is at the end. Please move it on top

2020-12-10 12:19 UTC, mcalmer approved these changes

2021-02-19 11:28 UTC, merged

2021-02-19 14:03 UTC, juliogonzalez commented
Huh!?

@hustodemon how is it that the github-actions bot created this comment :-?

This PR as a changelog entry.