Move dist upgrade allow vendor change sql to newer directory
uyuni-project/uyuni pull request #2996
Opened 2020-12-10 09:09 UTC by mseidl

Fixes issue when allow vendor change column sql file is in the an older schema directory. 
https://bugzilla.suse.com/show_bug.cgi?id=1179759
#13388 
port of https://github.com/SUSE/spacewalk/pull/13416

## What does this PR change?

Port of # **remove rest of file if this is a port**
## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2020-12-10 09:12 UTC, mcalmer requested changes
$> grep Version: uyuni-devel/schema/spacewalk/susemanager-schema.spec 
Version:        4.2.4

The correct schema migration directory would be 4.2.4-to-4.2.5

2020-12-10 09:32 UTC, juliogonzalez commented on schema/spacewalk/susemanager-schema.changes
> +- mv dist upgrade sql file so it gets picked up in schema upgrades (bsc#1179759)
```
- Move dist upgrade SQL file to the correct directory so it gets picked up in schema upgrades (bsc#1179759)

2020-12-10 09:32 UTC, juliogonzalez requested changes
Please fix the changelog.

2020-12-10 16:23 UTC, juliogonzalez commented
As discussed with @mcalmer, it seems you need to keep the changelog, but don't need to move the SQL file from one place to the other.

2020-12-11 14:17 UTC, juliogonzalez commented
Ping?

2020-12-11 15:40 UTC, mcalmer approved these changes

2020-12-11 15:42 UTC, juliogonzalez approved these changes

2020-12-11 15:42 UTC, merged