Testsuite: Add test for service pack migration
uyuni-project/uyuni pull request #3035
Opened 2020-12-16 15:57 UTC by calancha

## What does this PR change?
it adds a test for service pack migration on a SSH minion.

- testsuite/features/secondary/minssh_sp_migration.feature:
New test.

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/common_steps.rb:
Add the product we want to migrate.
Add an activation key for it.

- testsuite/features/support/twopence_init.rb
- testsuite/features/support/constants.rb:
- testsuite/documentation/cucumber-steps.md:
Add label 'ssh_spack_migrated_minion'.

- testsuite/run_sets/secondary_parallelizable.yml:
List the new test at the end of the YAML file.

## Links
https://github.com/SUSE/spacewalk/issues/11471

### Ports
- Manager-4.1: 

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

2020-12-16 16:01 UTC, calancha commented
Considering the slowlines of product synch at 4.0 compared with the newer branches, I am considering to not
port this test to 4.0; in my test machine, `Scenario: Kill running reposyncs` took a factor 3.7 larger at 4.0 VS 4.1.

2020-12-17 10:14 UTC, calancha commented
I added `SUSE-SSH-SP-MIGRATION-x86_64` to be explicit; if you don't like that we create it at `reposync` we can just drop it
as it is don't need it.

2020-12-17 11:47 UTC, srbarrios commented on testsuite/documentation/cucumber-steps.md
> +| SLES Salt SSH minion | ```$ssh_minion``` | ```$SSHMINION``` | ```"ssh_minion"``` or ```"ssh_spack_migrated_minion"``` | ```"minion"``` |
The minion of the thousand faces :trollface:

2020-12-17 11:48 UTC, srbarrios commented on testsuite/features/secondary/minssh_sp_migration.feature
> +@scope_salt_ssh
I will commit soon the Cucumber profiles, so you can port it :)

2020-12-17 11:50 UTC, srbarrios commented on testsuite/run_sets/secondary_parallelizable.yml
> +- features/secondary/minssh_sp_migration.feature
It will not work here.
You need to add it to the finishing yml, unless we want to create another extra stage for this case.

2020-12-17 11:52 UTC, srbarrios requested changes
I have only one request for change, we need to move the .feature to the finishing.yml, it can go to the yml file where we plan to run parallelizable features.

2020-12-17 15:11 UTC, Bischoff requested changes
Great test, thanks. See a few nitpicks.

Instead of putting this new feature at the beginning, we could try to put it at the end of `init_clients`.

Reason for that change is that, otherwise, we would be testing the older version (15 SP1) during most of the test suite. Maybe it's more interesting to test the newer version.

2020-12-17 15:11 UTC, Bischoff commented on testsuite/run_sets/finishing.yml
> +- features/finishing/minssh_sp_migration.feature
Move it 3 lines above, after srv_smbda

also change "this feature is destructive" comment to "these features are destructive"

2020-12-17 15:11 UTC, Bischoff commented on testsuite/features/reposync/srv_sync_products.feature
> +  Scenario: Add a 15 SP1 product
Cosmetical: add why you are doing it here

You will also need to sync SLES 15 SP2. I know this is already done elsewhere, but we should not depend on that other code. Maybe add a scenario, or use a tag `@sp_migration`, or add a warning in the code. But find something to protect ourselves from that other code changing.

2021-01-07 09:59 UTC, calancha commented
> Instead of putting this new feature at the very end, we could try to put it at the beginning, as last feature of `init_clients`.
> Reason for that change is that, otherwise, we would be testing the older version (15 SP1) during most of the test suite. Maybe it's more interesting to test the newer version (15 SP2) during most of test suite.
> 
> It's just a suggestion, maybe it comes with a zillion problems if we do like I say.

@Bischoff @srbarrios I've been exploring this approach during this week; my tests show that is feasable, in the sense,
that I don't observe tests breaking because of this approach (I see quite similar test results as in the CI).

Question: is it better open a new PR with the new approach?
Or instead, merge the new approach on the branch used in this PR?
What does make easier the review for you?

2021-01-07 10:14 UTC, srbarrios commented
> > Instead of putting this new feature at the very end, we could try to put it at the beginning, as last feature of `init_clients`.
> > Reason for that change is that, otherwise, we would be testing the older version (15 SP1) during most of the test suite. Maybe it's more interesting to test the newer version (15 SP2) during most of test suite.
> > It's just a suggestion, maybe it comes with a zillion problems if we do like I say.
> 
> @Bischoff @srbarrios I've been exploring this approach during this week; my tests show that is feasable, in the sense,
> that I don't observe tests breaking because of this approach (I see quite similar test results as in the CI).
> 
> Question: is it better open a new PR with the new approach?
> Or instead, merge the new approach on the branch used in this PR?
> What does it make easier the review for you?

As you wish. As you feel easier for you

2021-01-07 12:32 UTC, calancha commented
Superseded with https://github.com/uyuni-project/uyuni/pull/3090

2021-01-07 12:32 UTC, closed without merging