add missing unique index on suse tables
uyuni-project/uyuni pull request #3085
Opened 2021-01-06 16:17 UTC by rjmateus

Signed-off-by: Ricardo Mateus <rmateus@suse.com>

## What does this PR change?

During the development of "ISS Revamp: Data dumper implementation #12968" we found some tables with missing unique key constraints.
This PR will add a unique index to the following tables:
- suseproductchannel
- susemdkeyword
- suseupgradepath

## GUI diff

No difference.

## Documentation
- No documentation needed, schema changes.

## Test coverage
- No tests. Adding missing unique index.

## Links

Fixes https://github.com/SUSE/spacewalk/issues/13517
Tracks:
- Port to Manager 4.1

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-01-07 10:51 UTC, mcalmer requested changes
small typo

2021-01-07 10:51 UTC, mcalmer commented on schema/spacewalk/common/tables/suseMdKeyword.sql
> +CREATE UNIQUE INDEX susemdkeyword_lable_uq
typo in lable => label

2021-01-07 10:51 UTC, mcalmer commented on schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/802-add-missing-uq-index.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS susemdkeyword_lable_uq
typo as above

2021-01-07 13:43 UTC, rjmateus commented on schema/spacewalk/common/tables/suseMdKeyword.sql
> +CREATE UNIQUE INDEX susemdkeyword_lable_uq
thanks, MC. It's now corrected

2021-01-07 13:43 UTC, rjmateus commented on schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/802-add-missing-uq-index.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS susemdkeyword_lable_uq
thanks, MC. It's now corrected

2021-01-07 13:47 UTC, admd approved these changes
:+1:

2021-01-07 13:49 UTC, admd commented
Just noticed some tests are failing so please take a look.

2021-01-07 14:04 UTC, mcalmer approved these changes

2021-01-07 14:05 UTC, mcalmer requested changes
Sorry, had to revert my approval. It seems that java tests are failing. Please check why. It seems to be related to the change

2021-01-07 17:05 UTC, rjmateus commented
Test was corrected. They were inserting duplicated data on table SUSEProductChannel

2021-01-08 15:27 UTC, mcalmer approved these changes

2021-01-08 16:17 UTC, merged