Truncate author name in the changelog
uyuni-project/uyuni pull request #3094
Opened 2021-01-07 15:10 UTC by jvanz

## What does this PR change?

The table in the database to store the changelog has a varchar column of
128 to store the author name. Thus, the sync fails if, for some reason,
the author name has more chars. This commits changes the code to truncate
the author name in 128 chars.

Before:

Changelog author was not truncate. Allowing name with more than 128 chars

After:

The changelog author is truncated in 128 chars

- [ x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [x ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ x] **DONE**

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ x] Re-run test "changelog_test"
- [x ] Re-run test "backend_unittests_pgsql"
- [ x] Re-run test "java_pgsql_tests"
- [ x] Re-run test "schema_migration_test_oracle"
- [x ] Re-run test "schema_migration_test_pgsql"
- [ x] Re-run test "susemanager_unittests"
- [x ] Re-run test "javascript_lint"
- [ x] Re-run test "spacecmd_unittests"

2021-01-07 16:57 UTC, parlt91 approved these changes
LGTM
I tested if your changes actually fix the issue and can confirm that's the case.
Thank you very much for providing the fix. :smile: 
There is one thing to mention:
This is our upstream repository.
If you want to create a PTF for the customer you should base it on the product version that's affected in this case https://github.com/SUSE/spacewalk/tree/Manager-4.1
(there might be some changes between the two versions that can cause the ptf to fail to apply for the customer)
Please also open a PR with the very same changes for https://github.com/SUSE/spacewalk/tree/Manager-4.1 as well.
You can add me as a reviewer there and I will have another look as well.

2021-01-08 09:15 UTC, parlt91 commented
There is one thing I forgot. Since this is a bug fix please also reference the id of the bug in the changelog entry.
Like this: `Truncate author name in the changelog (bsc#1180285)`
Please do the same for your Manager-4.1 port

2021-01-08 09:17 UTC, parlt91 requested changes

2021-01-08 09:17 UTC, parlt91 commented on backend/spacewalk-backend.changes
> +- Truncate author name in the changelog
See my comment about the bug id for the changelog

2021-01-11 11:59 UTC, jvanz commented
> bsc#1180285

Done!

2021-01-11 12:00 UTC, jvanz commented
> There is one thing I forgot. Since this is a bug fix please also reference the id of the bug in the changelog entry.
> Like this: `Truncate author name in the changelog (bsc#1180285)`
> Please do the same for your Manager-4.1 port

Done!

2021-01-12 08:34 UTC, parlt91 approved these changes
Thanks looks good now. Thanks for helping us out on this. :+1:

2021-01-14 16:56 UTC, merged