improved actionchain error handling
uyuni-project/uyuni pull request #3169
Opened 2021-01-25 15:04 UTC by lucidd

## What does this PR change?

This PR adds error handling when the actionchain module `mgractionchains` is not present on a minion. Before this would not complete the actions and only a later cleanup task would set them to failed. Now those actions will be set to failed directly with the proper error message.

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/12826

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-01-27 17:05 UTC, mcalmer requested changes
The schema migration needs to move as uyuni was tagged today.

2021-01-27 17:05 UTC, mcalmer commented on schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/900-actionchaindispatch.sql
> +ALTER TABLE rhnActionChain DROP CONSTRAINT IF EXISTS rhn_actionchain_dispatched_ck;
Head got tagged today. So new schema migration dir is 4.2.5-to-4.2.6

2021-01-28 13:31 UTC, meaksh reviewed
Besides of what @mcalmer already mentioned about the schema, I've just spotted a minor thing to fix.

Other than that, let's give this a try :+1:

2021-01-28 13:31 UTC, meaksh commented on java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
>                                            ActionFactory.STATUS_PICKED_UP));
It seems we're duplicating `ActionFactory.STATUS_PICKED_UP` here.

IIUC this shoud be:
 ```suggestion
                             Arrays.asList(ActionFactory.STATUS_QUEUED,
                                           ActionFactory.STATUS_PICKED_UP));
```

2021-01-28 17:09 UTC, mbologna approved these changes

2021-01-31 13:56 UTC, mcalmer commented on schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/900-actionchaindispatch.sql
> +ALTER TABLE rhnActionChain DROP CONSTRAINT IF EXISTS rhn_actionchain_dispatched_ck;
JFYI - we just had to make another schema release. So just lookup the correct directory when the branch is open again to merge :-)

2021-02-01 15:27 UTC, meaksh commented on java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
>                                            ActionFactory.STATUS_PICKED_UP));
Hmmm, was this change missed after the force push?

2021-02-01 15:57 UTC, mcalmer approved these changes
I think we are good to go

2021-02-01 16:02 UTC, merged