Filter by package state name
uyuni-project/uyuni pull request #3227
Opened 2021-02-05 12:07 UTC by srbarrios

## What does this PR change?

**add description**

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-02-05 12:12 UTC, Bischoff requested changes
What about taking the occasion to simplify the implementation of￼

   `I remove package "..." from highstate`
   
Because you now spot the right package state, and that step loops over the whole table. But, if i am not wrong, you will get a single entry now, so mucher simpler code might be used.

2021-02-05 13:07 UTC, srbarrios commented
> What about taking the occasion to simplify the implementation of
> 
> `I remove package "..." from highstate`
> 
> Because you now spot the right package state, and that step loops over the whole table. But, if i am not wrong, you will get a single entry now, so mucher simpler code might be used.

Make sense.

2021-02-16 13:45 UTC, srbarrios commented
> What about taking the occasion to simplify the implementation of
> 
> `I remove package "..." from highstate`
> 
> Because you now spot the right package state, and that step loops over the whole table. But, if i am not wrong, you will get a single entry now, so mucher simpler code might be used.

@Bischoff if you don't mind, I prefer to keep this step as it is, it has some steps... that make me doubt how it can behave with a refactor, and I prefer to keep it, in any case it will only pass once on the loop, because we expect only one row.

This is the current implementation:
```
When(/^I remove package "([^"]*)" from highstate$/) do |package|
  event_table_xpath = "//div[@class='table-responsive']/table/tbody"
  rows = find(:xpath, event_table_xpath)
  rows.all('tr').each do |tr|
    next unless tr.text.include?(package)
    puts tr.text
    tr.find("##{package}-pkg-state").select('Removed')
    next if has_css?('#save[disabled]')
    steps %(
      Then I click on "Save"
      And I click on "Apply"
    )
  end
end
```

2021-02-16 13:50 UTC, Bischoff commented
> > What about taking the occasion to simplify the implementation of
> > `I remove package "..." from highstate`
> > Because you now spot the right package state, and that step loops over the whole table. But, if i am not wrong, you will get a single entry now, so mucher simpler code might be used.
> 
> @Bischoff if you don't mind, I prefer to keep this step as it is, it has some steps... that make me doubt how it can behave with a refactor, and I prefer to keep it, in any case it will only pass once on the loop, because we expect only one row.
> 
> This is the current implementation:
> 
> ```
> When(/^I remove package "([^"]*)" from highstate$/) do |package|
>   event_table_xpath = "//div[@class='table-responsive']/table/tbody"
>   rows = find(:xpath, event_table_xpath)
>   rows.all('tr').each do |tr|
>     next unless tr.text.include?(package)
>     puts tr.text
>     tr.find("##{package}-pkg-state").select('Removed')
>     next if has_css?('#save[disabled]')
>     steps %(
>       Then I click on "Save"
>       And I click on "Apply"
>     )
>   end
> end
> ```

We can do it later.

2021-02-16 14:00 UTC, Bischoff approved these changes
lgtm, we can do the small refactoring separately

2021-02-16 14:08 UTC, calancha approved these changes

2021-02-17 13:46 UTC, srbarrios commented
I finally had time to test it and works. Ready to be merged.

2021-02-18 09:43 UTC, juliogonzalez commented
Bypassing `java_pgsql_tests`, unrelated to this PR.

2021-02-18 09:43 UTC, merged