Speed up susemanager-nodejs-sdk-devel RPM build
uyuni-project/uyuni pull request #3291
Opened 2021-02-17 16:42 UTC by cbosdo

## What does this PR change?

That package has about 40000 files in the node_modules folder, and it
takes about 1.5h for rpmbuild to go over them.

I know this is super hacky, but let's reduce the number of files by
grouping them in an archive and uncompress the archive at RPM
installation time.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: rpm build speedup

- [X] **DONE**

## Test coverage
- No tests:  rpm build speedup

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-02-17 16:53 UTC, mcalmer requested changes
I fear this will never get accepted when we have to submit it to the official SUSE: namespace.

I think there should be a different solution

2021-02-17 16:55 UTC, cbosdo commented
> I fear this will never get accepted when we have to submit it to the official SUSE: namespace.
> 
> I think there should be a different solution

I fear that too, like I said it's hacky... but what other solution could we have? 1h+ build time for such a thing that is only used to build one other package isn't really acceptable

2021-02-17 17:06 UTC, cbosdo commented
hum... had a failure on OBS, would need more work anyway. I suppose the `%post` isn't executed by OBS

2021-02-18 12:03 UTC, mcalmer approved these changes

2021-02-19 11:33 UTC, juliogonzalez commented
@cbosdo I will ping autobuild so they can review this before I merge it (just in case)

2021-02-19 11:44 UTC, juliogonzalez approved these changes
LGTM, but I will request an extra review from autobuild. @cbosdo seems the description is outdated, can you update it? The more clear it is, the more easier will be for autobuild to understand and approve.

2021-02-22 10:04 UTC, juliogonzalez commented
Autobuild suggested we look at https://build.opensuse.org/package/view_file/openSUSE:Factory/mono-core/mono-core.spec?expand=1 lines 188-198 so we can exclude `node-js` tree from the dependency generation

2021-02-22 14:27 UTC, mcalmer commented
We tried the suggestions from the buildservice team without success.
Our spec file has already:
```
AutoReqProv: no
```
and the changed macros only help when trying to find entries for requires or provides.
But the problem is just processPackageFiles takes so long when used for 40000 files.
So I think this PR is the best what we can do.

2021-02-22 16:36 UTC, juliogonzalez commented
ACK, let's merge it tomorrow morning then.

@cbbayburt I guess you can prepare backports for SUSE Manager 4.1 and 4.0 as well.

2021-02-22 16:41 UTC, cbosdo commented
> @cbbayburt I guess you can prepare backports for SUSE Manager 4.1 and 4.0 as well.

I guess you meant me ;) but I'm not against @cbbayburt  to do the backport

2021-02-22 18:00 UTC, juliogonzalez requested changes
I just noticed that we need a changelog entry, as there are none since we promoted last time. Same for the 4.0 PR so we don't get a rejection from autobuild.

So I guess the best approach is adding the same changelog even for 4.1, so we have the same everywhere.

2021-02-23 09:46 UTC, juliogonzalez approved these changes

2021-02-23 09:46 UTC, merged