Move push_pacakage feature from core to secondary
uyuni-project/uyuni pull request #3318
Opened 2021-02-23 01:30 UTC by maximenoel8

Move push_pacakage feature from core to secondary

The changes have been tested

2021-02-23 08:14 UTC, ktsamis approved these changes
Looks great :100:

2021-02-23 09:53 UTC, maximenoel8 commented
@juliogonzalez Hi, you can ignore the error. There is no need of release note because it's a small testsuite change.

2021-02-23 09:59 UTC, mcalmer commented
@maximenoel8 you said "move", but the changes show only that you add that test to secondary* but not removed it from core.
This does not look correct. Would you please double check?

2021-02-23 11:01 UTC, ktsamis requested changes
Indeed @maximenoel8 you need to remove from here https://github.com/uyuni-project/uyuni/blob/master/testsuite/run_sets/core.yml#L16 Sorry I didn't catch it, I saw the rename

2021-02-23 11:01 UTC, ktsamis commented
Removing the label until the changes are made

2021-02-23 11:57 UTC, srbarrios commented
@maximenoel8 double-check with @calancha if this feature has not any dependency and can go to the parallelizable set of features, or it needs to stick into the secondary.yml file, where we have the features that have dependencies with others, and must run in a concrete order.

2021-02-24 03:23 UTC, maximenoel8 commented
> @maximenoel8 you said "move", but the changes show only that you add that test to secondary* but not removed it from core.
> This does not look correct. Would you please double check?

Good catch, indeed I forget to remove from core on this second PR.

2021-02-24 03:27 UTC, maximenoel8 commented
> @maximenoel8 double-check with @calancha if this feature has not any dependency and can go to the parallelizable set of features, or it needs to stick into the secondary.yml file, where we have the features that have dependencies with others, and must run in a concrete order.

I check if the package was call in any other part of the code and seems to be a standalone.

2021-02-24 12:20 UTC, calancha commented
@maximenoel8 
- Please, move `srv_push_package.feature` in `secondary_parallelizable.yml`
   above; together with the rest of `srv_` features.
- Drop `srv_push_package.feature` also from:
```
virtualization.yml
sle-updates.yml
refhost.yml
```

- According with my checks, the following Scenario is not needed anymore:
```
  Scenario: Download the SSL certificate
    When  I download the SSL certificate
    And I make the SSL certificate available to zypper
```

I have seen that the SSL certificate is downloaded and the link created
when we run `sle_client.feature`.  Note that, we only refer to these two
steps in this feature.

Please, double-check it; if I am right, then delete such a scenario from
the feature and their step definitions from `common_steps.rb`.

2021-03-02 10:53 UTC, Bischoff requested changes
Please apply Tino's changes from last comment.

Apart from that, LGTM. Thanks for that change, the more we can remove from core, the best.

2021-03-15 08:14 UTC, maximenoel8 commented
Add the change to the pull requests. After some testing, the change are working fine !

2021-03-15 10:37 UTC, ktsamis approved these changes
We are doing 2 things now, moving the push_package feature to secondary and removing the "Download the SSL certificate" feature and implementation. For now this is fine if it's tested. Next time please 2 PRs with clear goals.

2021-03-16 01:43 UTC, maximenoel8 commented
> We are doing 2 things now, moving the push_package feature to secondary and removing the "Download the SSL certificate" feature and implementation. For now this is fine if it's tested. Next time please 2 PRs with clear goals.

OK sorry. Download SSL was only use in push_package. That's why I did it in the same PR.

2021-03-16 08:01 UTC, Bischoff requested changes
I am okay to remove Scenario `Download the SSL certificate`, but what was it needed for, and why isn't it needed anymore? We would need some context here.

2021-03-16 08:01 UTC, Bischoff commented on testsuite/features/secondary/srv_push_package.feature
> -  Scenario: Download the SSL certificate
What was this scenario needed for?

2021-03-16 08:55 UTC, mcalmer commented
The `Download the SSL certificate` needs a bit or research. Originally I added it to make rhnpush work.
rhnpush works only out of the box then it uses SSL. But to use SSL, the CA certificate store must be available.
The default config say, that it should look for it at `/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT` which is available on every registered client. **But** we execute rhnpush on the "Server". This step was there to download the SSL certificate and make it available on the server at the expected path. See Commit fa3fc505a963edc104fa112e46b3b126ca8964b7

But it seems later this was missunderstand and Commit 2667a2c51cf71e2e017a992202550c04190bb3e8 changed it to execute it on the "client". But from my point of view this is not required on the client as it should be there already after a successful registration.

1. check, how rhnpush can be executed on the server using SSL? Where does the certificate come from?
2. Try to remove that step from the client. From my point of view this is not needed. At least not on the client.

2021-03-16 09:09 UTC, maximenoel8 commented
I removed the SSL part from the PR and will create a card for that. Thanks for you feedback !

2021-03-16 09:19 UTC, Bischoff approved these changes

2021-03-16 09:39 UTC, srbarrios approved these changes

2021-03-17 23:37 UTC, merged