Fix insecure JXM configuration
uyuni-project/uyuni pull request #3542
Opened 2021-04-12 15:51 UTC by witekest

## What does this PR change?

The change restricts access to Java Remote Method Invocation to
`localhost` to prevent unauthorized remote code execution.

## GUI diff

No difference.

## Documentation
- No documentation needed: Open RMI ports are meant to be used by JMX exporter only and not by the users.

## Test coverage
- No tests: Tests updated

- [x] **DONE**

## Links

Fixes # https://bugzilla.suse.com/show_bug.cgi?id=1184617

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-04-13 08:22 UTC, meaksh reviewed
Thanks @witekest - the changes on the SLS files look good to me :+1:

I only miss the necessary changelog entry for `susemanager-sls` at `susemanager-utils/susemanager-sls/susemanager-sls.changes` including the bsc reference.

2021-04-13 08:25 UTC, mcalmer commented
@witekest beside of the changelog problem: how we fix the customer configuration when he has monitoring enabled and update the package? AFAIK just installing the package does not change the config files, right?

2021-04-13 08:32 UTC, witekest commented
> how we fix the customer configuration when he has monitoring enabled and update the package? AFAIK just installing the package does not change the config files, right?

Good point. Disabling and enabling monitoring should work. Any other idea than documenting it?

2021-04-13 08:33 UTC, juliogonzalez requested changes
Changelog missing, and same concerns as those from @mcalmer.

Looks to me that we'd need to document at the release notes that users/customers should apply the highstate to get fixed? Any other better approach?

2021-04-13 08:40 UTC, juliogonzalez commented
> Good point. Disabling and enabling monitoring should work. Any other idea than documenting it?

Applying the highstate is not enough :-?

2021-04-13 08:44 UTC, mcalmer commented
> > Good point. Disabling and enabling monitoring should work. Any other idea than documenting it?
> 
> Applying the highstate is not enough :-?

No, we talk about the "Server". You cannot call highstate for the server.

@witekest will "mgr-monitoring-ctl status" show it as enabled after the update when it was enabled before?

2021-04-13 08:50 UTC, mcalmer commented
This is how the Configuration page would look like:

![image](https://user-images.githubusercontent.com/1038917/114524972-fb6f8b80-9c45-11eb-821c-d219d120b9ba.png)

2021-04-13 09:55 UTC, mcalmer requested changes

2021-04-13 09:55 UTC, mcalmer commented on susemanager-utils/susemanager-sls/salt/srvmonitoring/removejmxprops.sls
> +    - name: sed -i 's/JAVA_OPTS="(.*)-Dcom\.sun\.management\.jmxremote\.host=localhost(.*)"/JAVA_OPTS="\1 \2"/' {{remove_jmx_props.file}}
This failed with: 

  "sed: -e expression #1, char 90: invalid reference \\2 on `s' command's RHS"

Seems `(` needs to be escaped

2021-04-14 07:20 UTC, mcalmer commented
I am unsure what we discussed: do we want to fix the configuration via %post script or do we want just to document it?
Please also check, if the salt state restart the jmx exporters with the new config when it gets changed via the configuration.

2021-04-14 08:34 UTC, witekest commented
After setting `JAVA_OPTS` _Tomcat_ and _Taskomatic_ have to be restarted to apply the changes. I think `susemanager-sls.spec %post` is not the right place to implement it.

2021-04-14 09:14 UTC, witekest commented
@juliogonzalez has pointed to me that all the services have to be stopped during the update anyway.
@mcalmer, could you confirm that `susemanager-sls.spec %post` is the place you have meant to implement it?

2021-04-14 09:56 UTC, mcalmer commented
I think in %post we should do the following test:

```
if service prometheus_jmx_tomcat is enabled and /etc/sysconfig/tomcat does not contain "jmxremote.host="; then
  add ... jmxremote.host=locahost to config
endif
```

same for taskomatic.

Additionally we should review the `spacewalk-service start|stop` . AFAIK it does not handle monitoring which is not so good.

2021-04-15 07:58 UTC, witekest commented
> Additionally we should review the `spacewalk-service start|stop` . AFAIK it does not handle monitoring which is not so good.

We could be updating `/etc/rhn/service-list` file. Restarting exporters is not needed for this PR to take effect though. Do we have another reason for restarting exporters?
In any case I think we should handle it in a separate PR.

2021-04-15 10:40 UTC, mcalmer approved these changes
LGTM

2021-04-15 10:42 UTC, mcalmer commented
> > Additionally we should review the `spacewalk-service start|stop` . AFAIK it does not handle monitoring which is not so good.
> 
> We could be updating `/etc/rhn/service-list` file. Restarting exporters is not needed for this PR to take effect though. Do we have another reason for restarting exporters?
> In any case I think we should handle it in a separate PR.

Yes, for a separate PR. But be careful about service-list. AFAIK this is not used anymore. There is a systemd target and other funny things.
I would suggest to play around with systemd dependencies. What about "binding" the JMX exporter to the main service.
It does not make sense to run a tomcat jmx exporter when tomcat itself is not running.

2021-04-15 13:55 UTC, juliogonzalez approved these changes
Seems to be OK. If you tested that the change to susemanager-sls.spec are working fine, then go ahead and merge :-)

2021-04-15 16:16 UTC, merged