Let spacecmd parse empty|null parameters
uyuni-project/uyuni pull request #3778
Opened 2021-05-18 12:07 UTC by ncounter

https://github.com/uyuni-project/uyuni/issues/3525

## What does this PR change?

Let `spacecmd` parse empty arguments when there is nothing between the _item list separator_ . 

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: 

- [x] **DONE**

## Test coverage
- No tests: adapted and added

- [x] **DONE**

## Links

Fixes # https://github.com/uyuni-project/uyuni/issues/3525
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-05-18 12:14 UTC, hustodemon approved these changes
LGTM, although I'd like an additional person to review too.

2021-05-18 12:20 UTC, brejoc approved these changes
lgtm!

2021-05-18 12:30 UTC, meaksh approved these changes

2021-05-18 12:33 UTC, meaksh requested changes
The changes look good but just realized there is a "spacecmd" test failing for this PR: https://ci.suse.de/job/uyuni-prs-spacecmd_unittests-pipeline/4952/console

@ncounter could you take a look to that test? Thanks!!

2021-05-18 13:29 UTC, ncounter commented
> The changes look good but just realized there is a "spacecmd" test failing for this PR: https://ci.suse.de/job/uyuni-prs-spacecmd_unittests-pipeline/4952/console
> 
> @ncounter could you take a look to that test? Thanks!!

Argh, of course. I did it in the wrong place. Fixed now. :+1:

2021-05-19 07:47 UTC, jordimassaguerpla commented
Congratulations! Acceptance tests passed :woman_dancing: :man_dancing: 

* core tests :heavy_check_mark: 
* spacecmd functional scope :heavy_check_mark:

2021-05-19 10:51 UTC, juliogonzalez commented
@ncounter can this be merged or do we need the approval from @meaksh?

2021-05-19 10:54 UTC, ncounter commented
> @ncounter can this be merged or do we need the approval from @meaksh?

@juliogonzalez I actually fixed the test that was failing pointed out by him, other than that he already approved it. If you are fine to merge it already, I don't have anything else to fix or change.

2021-05-19 10:56 UTC, juliogonzalez commented
Merging. I think the java_pgsql_tests failures are unrelated.

2021-05-19 10:56 UTC, merged