Fix channel name for Debians to sync
uyuni-project/uyuni pull request #3857
Opened 2021-06-08 09:34 UTC by ktsamis

## What does this PR change?

Fixes the channel name for Debians to sync when running mgr-create-bootstrap-repo

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes no issue, directly from testsuite review
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-06-08 09:50 UTC, srbarrios approved these changes

2021-06-08 10:17 UTC, lkotek approved these changes
LGTM :+1:

2021-06-08 11:51 UTC, Bischoff approved these changes
Hmmm indeed

```
suma-bv-42-srv:~ # mgr-create-bootstrap-repo | grep debian
12. debian10-amd64
13. debian9-amd64
```

I was pretty sure I had tested this :-(

2021-06-08 15:56 UTC, Shirocco88 commented
**IMHO: There are more Lines to be fixed:**

**Pattern "debian-9-pool-amd64"**
https://github.com/uyuni-project/uyuni/blob/2686652719f8dcce6d4f5abc8bc3ef2e61ad1f05/testsuite/features/support/constants.rb#L200
https://github.com/uyuni-project/uyuni/blob/2686652719f8dcce6d4f5abc8bc3ef2e61ad1f05/testsuite/features/support/constants.rb#L232

**Pattern "debian-10-pool-amd64"**
https://github.com/uyuni-project/uyuni/blob/2686652719f8dcce6d4f5abc8bc3ef2e61ad1f05/testsuite/features/support/constants.rb#L201
https://github.com/uyuni-project/uyuni/blob/2686652719f8dcce6d4f5abc8bc3ef2e61ad1f05/testsuite/features/support/constants.rb#L233

2021-06-12 09:50 UTC, Shirocco88 requested changes
Hint: these changes "testsuite/features/support/constants.rb" are also included in https://github.com/uyuni-project/uyuni/pull/3874

please also fix Pattern "debian-9-pool-amd64"
Line 200
Line 232

and Pattern "debian-10-pool-amd64"
Line 201
Line 233

2021-06-12 12:14 UTC, Bischoff commented
Let's keep my PR that also addresses CentOS 8 issues.

2021-06-12 12:14 UTC, closed without merging