Update sslToolConfig.py
uyuni-project/uyuni pull request #3939
Opened 2021-07-04 16:04 UTC by sbluhm

Updated added lines to also build on Python 2

## What does this PR change?

Lines were added that only build on Python 3. This PR updates them to also build on Python 2

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: No functional changes.

- [X] **DONE**

## Test coverage
- No tests: already covered

- [X] **DONE**

## Links

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-07-04 16:41 UTC, Shirocco88 commented
@sbluhm Why do you want to re-add python2 ?
python2 isn't supported any more.

2021-07-04 17:11 UTC, sbluhm commented
I don't :). Spec file still builds Python 2 though. I would like approval first to remove all Python 2 code from the spec file (which would then require more testing). So this would be the quick compromise to get RHEL8 building again.

2021-07-05 08:24 UTC, sbluhm commented
@Shirocco88 Created #3940 which removes Python 2 completely from the spec file. So we have both choices to move forward.

2021-07-07 07:32 UTC, cbosdo requested changes
Not working for python2 nor for python3

2021-07-07 07:32 UTC, cbosdo commented on spacewalk/certs-tools/sslToolConfig.py
> +                f"error: {}\n".format(ret, sstr(errstream.read())) )
This is still containing python3-only features:
* f-strings
* parentheses concatenation

A proper fix would be:
```python
    sslerrmsg = "non-zero exitcode.\n" \
                "If you ran configure-proxy.sh, try copying again the certs from the SUSE Manager Server\n" \
                "exit-code: {}\n" \
                "error: {}\n".format(ret, sstr(errstream.read()))
```

2021-07-07 07:42 UTC, sbluhm commented
going with #3940

2021-07-07 07:42 UTC, closed without merging