susemanager: Package 'snapper' is now optional
uyuni-project/uyuni pull request #4087
Opened 2021-08-03 16:45 UTC by sbluhm

## What does this PR change?

Package `snapper` is required during setup for creating btrfs volumes using `mksubvolume`.
This change makes the `snapper` package optional.
Should the package be required and not installed at setup time, it will automatically be installed.
A friendly message is displayed should the automatic installation fail.

Background: Snapper and btrfs-progs are not available on Enterprise Linux 8. Making the packages optional allows system admins decide whether they would like to install 3rd party packages, create their own package or not use btrfs.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- No tests: Manually tested.

Code works on Leap and AlmaLinux. Installation tested manually with and without package on AlmaLinux installation.
Build has been tested successfully on
 epel-8-x86_64 
 opensuse-leap-15.3-x86_64 

- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-08-19 06:42 UTC, sbluhm commented
@mcalmer , can you please review or assign reviewers?

2021-08-23 14:52 UTC, mcalmer requested changes

2021-08-23 14:52 UTC, mcalmer commented on susemanager/bin/mgr-setup
> +        if ! [ $? -eq 0 ]; then
```suggestion
        if [ $? -ne 0 ]; then
```
I find not + equal check too confusing.

2021-08-24 08:30 UTC, mcalmer approved these changes

2021-08-25 06:45 UTC, merged