CI: parallelize bootstrap clients
uyuni-project/uyuni pull request #4221
Opened 2021-09-16 10:16 UTC by jordimassaguerpla

## What does this PR change?

Instead of bootstrapping each client and waiting for it, let's first
bootstrap all of them and then wait for them to appear in the system
list.

This way, we are parallelizing the bootstrap process. Thus, the total
time should be smaller, meaning faster.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed
- [X] **DONE**

## Test coverage
- No tests

- [X] **DONE**

## Links

N/A

- [X] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-09-16 10:17 UTC, jordimassaguerpla commented
This is an idea that I had. I have not tested it but I wanted to know what QEng thing about it.

2021-09-16 10:43 UTC, jordimassaguerpla commented
Hi! This is nor urgent nor planned, so feel free to review it when  you have some spare time, no pressure on this one. Thanks.

2021-09-16 12:38 UTC, srbarrios requested changes
I don't like that approach.
We should just run it using the cucumber:parallel command in the stage that requires it.

There is no need at all of splitting these features. Just use the rake task of cucumber:parallel where you need it.

In CI, we decided to don't parallelize at all for now... for several reasons like the reporting, but I hope that we can soon start enabling at least some parts like this.

2021-09-16 12:51 UTC, jordimassaguerpla commented
IIRC, we can't run the client tasks in parallel because the server keeps the information on what the user is in the menu, so we cannot be in different places in parallel ... do you know what I mean? Did I got it right? If so, we cannot run it in parallel, unless we had a separate user for each client.

Unless, we don't wait for the bootstrap to complete. The idea here is to basically split the bootstrap tests into two, one that does the bootstrap, and another one that does the "wait". This way , we can bootstrap all of them, and then do the wait:

"click on bootstrap sle"
"click on bootstrap centos"
"click on bootrsap ubuntu"
etc.
"wait for sle to appear in system list"
"wait for centos to appear in system list"
"wait for ...."
etc.

2021-09-16 12:53 UTC, jordimassaguerpla commented
The idea at the end is just a copy of the "fork and wait" pattern you could use when programming in parallel.

2021-10-05 07:42 UTC, jordimassaguerpla commented
I tried running this PR. I got this error for almost each client:

```Given I am authorized for the "Admin" section

Message:

    unexpected alert open: {Alert text : }```

Looks like there is an unexpected alert:

![image](https://user-images.githubusercontent.com/1148215/135980771-444b1e18-247f-4192-93ac-95d1189eefb0.png)

Running with this error took 5 minutes less of 30 minutes.

Why are we seeing this alert?

2021-10-05 07:42 UTC, jordimassaguerpla commented
![image](https://user-images.githubusercontent.com/1148215/135981098-7e44a549-0a85-4a5d-8205-e40c49cb2ee6.png)

2021-10-05 07:44 UTC, jordimassaguerpla commented
```All of your systems are actively checking into Uyuni at this time```

Might be because the different clients are bootstrapping .... which makes sense. Then, how can I make cucumber do not fail on this alert?

2021-10-05 16:39 UTC, jordimassaguerpla commented
I tried changing the default but did not worked https://github.com/uyuni-project/uyuni/pull/4221/commits/3c9b252be9b6690d019414fefde28130b38bb5aa .

In any case, this would only save 5 minutes, which is not much. Other optimizations saved 15 or 30 minutes.

Given is not a big gain, I won't push for this if QE does not like it (Oscar in this case). We can try again a different approach when tests are parallelized.

2021-10-05 16:39 UTC, closed without merging