spacewalk-proxy: remove unnecessary dependencies to Squid
uyuni-project/uyuni pull request #4480
Opened 2021-11-17 13:05 UTC by moio

## What does this PR change?

Removes unnecessary dependencies between packages, this is useful for the ongoing containerization effort.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-11-17 13:09 UTC, moio commented
@mcalmer I could not see a good reason to keep the requirement in e337d2d32537ddd2c2c46b16c005c99b837dc5d1 - tried out building a branch of this package from my home project and installation/operation works as expected.

Do you see something I might have missed about it?

2021-11-17 13:20 UTC, mcalmer commented
@moio take care, that squid is in our proxy pattern. In case we install the product on a real system, squid is needed to be installed.

2021-11-17 13:34 UTC, moio commented
@mcalmer it is not, but `squid` is still pulled in by `spacewalk-proxy-management`. Is that OK or we want an explicit mention in the pattern?

2021-11-17 13:40 UTC, mcalmer commented
@moio Ok, this will work.

2021-11-22 10:58 UTC, mcalmer approved these changes
Maybe you need a changelog. This package is not touched so often and to submit it we need at least 1 changelog entry.

2021-11-22 11:35 UTC, juliogonzalez commented
@moio yes, a changelog entry is needed.

2021-11-23 16:31 UTC, moio commented
PR test results (no difference from `master` at the time of writing): https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/894/testReport/

2021-12-14 10:47 UTC, mcalmer requested changes

2021-12-14 10:47 UTC, mcalmer commented on proxy/proxy/spacewalk-proxy.changes
> +
Wrong format. Please remove the header

2021-12-16 09:39 UTC, moio commented on proxy/proxy/spacewalk-proxy.changes
> +
Sorry about that, fixed

2021-12-16 10:56 UTC, mcalmer approved these changes

2021-12-16 10:59 UTC, merged