Fix traceback on spacewalk-repo-sync --show-packages ... (bsc#1193238)
uyuni-project/uyuni pull request #4538
Opened 2021-12-06 08:46 UTC by vzhestkov

## What does this PR change?

Fix traceback on calling `spacewalk-repo-sync --show-packages ...`

## GUI diff

No difference.

## Documentation
- No documentation needed: only internal and user invisible changes

## Test coverage
- No tests: This feature was not covered with the tests. Looking for the way to test it. TBD

## Links

Fixes https://github.com/SUSE/spacewalk/issues/16473

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2021-12-13 12:20 UTC, meaksh approved these changes

2021-12-13 14:05 UTC, agraul requested changes
As you wrote in the PR, there are no tests yet. IIRC @SchoolGuy wanted to help out. Is that correct or do I remember something wrong?

2021-12-13 14:07 UTC, vzhestkov commented
@agraul I remember the same :+1:

2022-03-21 14:40 UTC, vzhestkov commented
@agraul I've created followup card to add the tests for the feature fixed with this PR: https://github.com/SUSE/spacewalk/issues/17310
Let's merge it as it is now and add the tests later

2022-04-29 08:18 UTC, agraul approved these changes

2022-05-11 08:29 UTC, merged