Refactor product cucumber names
uyuni-project/uyuni pull request #4674
Opened 2022-01-14 11:51 UTC by vandabarata

## What does this PR change?
Removed the $PRODUCT references in the Cucumber tests, both in the Gherkin steps and the steps themselves.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- Cucumber tests were added

- [x] **DONE**

## Links

Fixes #5885 

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-01-14 12:46 UTC, ktsamis approved these changes
Looks great, great job Vanda, super quick as well. :100:

2022-01-14 14:38 UTC, srbarrios approved these changes

2022-01-18 15:06 UTC, Etheryte requested changes
It seems there's some issues with the set of commits in this branch at the moment, please try rebasing your original commits onto master, or some other approach to fix the changeset. For context, please see both the commits and the changes tab on the pull request. Feel free to let me know if something's unclear.

2022-01-20 16:20 UTC, Etheryte approved these changes
Thanks a lot for fixing this up, looks good. 🙂

2022-01-26 11:05 UTC, merged