ReportDB User: prevent to modify the main users
uyuni-project/uyuni pull request #4878
Opened 2022-02-21 16:31 UTC by mbussolotto

## What does this PR change?

- do not allow to change SUMA DB admin user
- do not allow to change ReportDB DB admin user
- remind that postgres in case-insensitive

## GUI diff

No difference.

- [x] **DONE**

## Documentation
N/A

- [x] **DONE**
N/A

## Test coverage
- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/16989

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-02-21 16:40 UTC, mbussolotto commented
By now I decided to avoid changes to admin user because the script is meant to be used just for the read-only reportdb user. The other option would be to allow the script to modify also the admin password (in this case, we need to modify also the `rhn.conf` file). Not sure which is the best option, your thoughts and opinions are welcomed :)

2022-02-22 16:51 UTC, lucidd approved these changes

2022-02-25 08:25 UTC, mcalmer requested changes

2022-02-25 08:25 UTC, mcalmer commented on spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user
> +ADMIN_USERS=$(echo "SELECT usename FROM pg_catalog.pg_user WHERE usesuper='t' " | spacewalk-sql -i | tail -n +3 | head -n -2 | tr '[:upper:]' '[:lower:]')
`spacewalk-sql -i` is using the "interactive" mode. This is not what you want.
I think you want `spacewalk-sql --select-mode`

2022-02-25 08:57 UTC, mackdk approved these changes

2022-02-25 14:00 UTC, mcalmer approved these changes

2022-02-25 14:03 UTC, merged