WIP: Demo for deprecating `susemanager-frontend`
uyuni-project/uyuni pull request #4950
Opened 2022-03-04 19:57 UTC by Etheryte

## What does this PR change?

**add description**

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_oracle"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-03-16 11:06 UTC, Etheryte commented
@agraul @juliogonzalez Sorry for the bother, if you have the time, could you please take a look and help me figure out why I can't get this to build correctly? The core of the related changes are to [`web/spacewalk-web.spec`](https://github.com/uyuni-project/uyuni/pull/4950/files#diff-325898a27431b9480c5b9155e098708b5e02388919ca187e0f9578183353bead) and to [`web/setup.sh`](https://github.com/uyuni-project/uyuni/pull/4950/files#diff-546e6f71180f889655e24bda285cd0ef1f861b1c113ca3a2ae5a9c72a9e87334).

2022-03-16 11:09 UTC, juliogonzalez commented
> could you please take a look and help me figure out why I can't get this to build correctly?

What's the error?

2022-03-16 11:12 UTC, Etheryte commented
The error is the one outlined in the PR description, when I try to use `rel-eng/build-packages-local-obs.sh` I get

```
RPM build errors:
Bad file: /tmp/push-packages-to-obs/SRPMBUILD/rpmbuild-spacewalk-webrw879qlk/SOURCES/node-modules.tar.gz: No such file or directory
```

I've outlined more details and what I've done exactly as well in the PR description, I just didn't want to ping you with a wall of text.

2022-03-16 11:27 UTC, juliogonzalez commented
> The error is the one outlined in the PR description, when I try to use `rel-eng/build-packages-local-obs.sh` I get
> 
> ```
> RPM build errors:
> Bad file: /tmp/push-packages-to-obs/SRPMBUILD/rpmbuild-spacewalk-webrw879qlk/SOURCES/node-modules.tar.gz: No such file or directory
> ```
> 
> I've outlined more details and what I've done exactly as well in the PR description, I just didn't want to ping you with a wall of text.

How was `susemanager-nodejs-modules.tar.gz`created in the past? `node-modules.tar.gz` should be created in the same way for `spacewalk-web`, so it's added to the sources.

This was some magic outside of my area of knowledge, maybe you need to check with Dario?

2022-03-16 11:39 UTC, Etheryte commented
As far as I know (but I could be wrong), there was no logic beyond what was in [`susemanager-frontend/susemanager-nodejs-sdk-devel/setup.sh`](https://github.com/uyuni-project/uyuni/pull/4950/files#diff-b23a8ca69910d18aaf19f8c7a770cbaf23461193dbe8d62e0cae0a3c9f2de360). However after I moved the logic over to [`web/setup.sh`](https://github.com/uyuni-project/uyuni/pull/4950/files#diff-546e6f71180f889655e24bda285cd0ef1f861b1c113ca3a2ae5a9c72a9e87334), I get no dice and the error shown above, even after I manually created the file and added it to my fork on OBS. @ncounter do you know what I could be doing wrong?

2022-03-16 12:11 UTC, juliogonzalez commented
Discussed at Slack. 

The tarball was created not at the `web/` but at `/web/html/src`. Adding a `mv` to `setup.sh` fixes the issue.

2022-03-17 17:15 UTC, Etheryte commented
This is ready for review. In short, the changes can be summarized as follows:  

 - `susemanager-frontend` along with `susemanager-nodejs-sdk-devel` no longer exists.  
 - All the dependencies and build logic was moved over to `spacewalk-web`.
 - `web/html/src/build.js` was updated to no longer require Webpack as a standalone executable.
 - Github actions etc were updated.

I have a build success on [my fork of spacewalk-web on obs](https://build.opensuse.org/package/show/home:Etheryte:branches:systemsmanagement:Uyuni:Master/spacewalk-web).  

Please let me know if there's anything I missed, or you feel is left over.

2022-03-18 13:09 UTC, juliogonzalez requested changes

2022-03-18 13:09 UTC, juliogonzalez commented on web/spacewalk-web.spec
> +%{!?nodejs_sitelib:%define nodejs_sitelib %{_prefix}/lib/node_modules}
IIRC this PR correctly, you need to add the license from the old nodejs-sdk package to this package, right?

Also remember to remove the old nodejs-sdk packages from `rel-eng/packages`

2022-03-18 13:10 UTC, juliogonzalez commented on web/spacewalk-web.spec
> +%{!?nodejs_sitelib:%define nodejs_sitelib %{_prefix}/lib/node_modules}
As similar to @agraul I just reviewed specs and changelogs, but not the rest of the changes, as I don't have enough knowledge to judge :-)

2022-03-28 10:52 UTC, juliogonzalez approved these changes
Should be OK now. Approved.

2022-03-29 13:16 UTC, Etheryte commented
Merging this now so I have time to address if any build issues come up before the end of the day.

2022-03-29 13:16 UTC, merged