Generate reportdb documentation
uyuni-project/uyuni pull request #5282
Opened 2022-04-26 10:10 UTC by mackdk

## What does this PR change?

This PR adds the comments and the script needed to generate the reporting database documentation. It is composed of three main parts:

- The SQL script to add the comments and prepare the database for the analysis. These are located in the directory `schema/reportdb/postgresql/docs` as this script are PostgreSQL specific.
- The support files needed to generated the documentation, located in the `schema/reportdb/docs` directory. There are the java libs for schemaspy and the postgresql jdbc driver, the html template, the fonts and the property file with the schemaspy settings
- The scripts to execute the process in a docker container located in `susemanager-utils/testing`

## GUI diff

No difference.

- [X] **DONE**

## Documentation

Documentation is implemented through SQL comments and foreign keys added to the database and generated using the SchemaSpy tool which is bundled inside the `schema/reportdb/docs` directory. After the script are executed the database is built updated and examined in a docker container and the result of the operation is the HTML documentation.

- [X] **DONE**

## Test coverage
- No tests: No code changes

- [X] **DONE**

## Links

Fixes SUSE/spacewalk/issues/16564

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-04-26 10:12 UTC, mackdk commented
Continuation of https://github.com/uyuni-project/uyuni/pull/5233

2022-04-26 10:32 UTC, mcalmer requested changes
One change needed for the latest changes in the ChannelPackage table

2022-04-26 10:32 UTC, mcalmer commented on schema/reportdb/postgres/docs/tables/ChannelPackage.pre
> +  IS 'The timestamp of when this data was last refreshed.';
```suggestion
COMMENT ON COLUMN ChannelPackage.synced_date
  IS 'The timestamp of when this data was last refreshed.';
```
Remove dropped columns

2022-04-26 10:34 UTC, mcalmer commented on susemanager-utils/testing/docker/scripts/generate-reportdb-docs.sh
> +java -cp $(build-classpath ongres-scram) -jar /root/schemaspy.jar -configFile $CONFIG_FILE -dp $(build-classpath postgresql-jdbc)
The download of `schemaspy.jar` happens not here?

2022-04-27 14:39 UTC, mcalmer approved these changes

2022-04-27 21:19 UTC, merged