Fix rel-eng changelog for container images
uyuni-project/uyuni pull request #5369
Opened 2022-05-05 15:36 UTC by ncounter

## What does this PR change?

$subject

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: rel-eng stuff

- [x] **DONE**

## Test coverage
- No tests: rel-eng stuff

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-05-09 09:14 UTC, juliogonzalez reviewed
Did you check this against a test project, so see what whill happen on the next submission after the changelog entry is added?

2022-05-09 10:14 UTC, ncounter commented
> Did you check this against a test project, so see what whill happen on the next submission after the changelog entry is added?

Yes I extracted the slice of code and tested on the local project folder, and this is the behavior I see is the one I expect:
- If there is no changelog entry with the _version string_, it adds one.
- If there is one with the _version string_, it compares the value, if it is different it adds one.
- If there are multiple changelog with the _version string_, it takes only the first one (first at the top = latest) and it does the comparison as above
all that said compared to the version in `/web/conf/rhn_web.conf`

2022-05-09 10:49 UTC, juliogonzalez requested changes
One minor suggestion, abut what we discussed on Friday.

Make sure you retest, just in case! :-D

2022-05-09 10:49 UTC, juliogonzalez commented on rel-eng/push-packages-to-obs.sh
> +      # add a changelog entry if it is not yet up to the latest version
One minor suggestion, according to what we discussed 
```suggestion
      # add a changelog entry if it is not yet up to the latest version
      CHANGELOG_TEMPLATE="Update the image version to"
```

2022-05-09 10:49 UTC, juliogonzalez commented on rel-eng/push-packages-to-obs.sh
> +      CHANGELOG_PKG_VERSION=$(echo ${CHANGELOG_PKG_VERSION} | sed -n 's/.*Update\sthe\simage\sversion\sto\s\(.*\)$/\1/p')
```suggestion
      CHANGELOG_PKG_VERSION=$(echo ${CHANGELOG_PKG_VERSION} | sed -n "s/.* ${CHANGELOG_TEMPLATE} (.*\)$/\1/p")
```

2022-05-09 10:49 UTC, juliogonzalez commented on rel-eng/push-packages-to-obs.sh
> +        ${OSC} vc ${SRPM_PKG_DIR} -m "Update the image version to ${PRODUCT_VERSION}"
```suggestion
        ${OSC} vc ${SRPM_PKG_DIR} -m "${CHANGELOG_TEMPLATE} ${PRODUCT_VERSION}"
```

2022-05-10 10:08 UTC, ncounter commented
Closing because of https://github.com/uyuni-project/uyuni/pull/5401

2022-05-10 10:08 UTC, closed without merging