fix bootstrap repo handling for SLE Micro
uyuni-project/uyuni pull request #5441
Opened 2022-05-13 14:27 UTC by mcalmer

## What does this PR change?

SLE Micro was using not existing bootstrap repo path. Detect SLE Micro properly and define an own path for it.
Also define bootstrap repo definitions and package list (no traditional tools)

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage
- No tests: **manual**

- [ ] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17793
Tracks 

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-05-13 14:31 UTC, vzhestkov commented
@mcalmer could you please also adjust https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
There is a card to unify the code of bootstrap and preflight script (to prevent copying almost the same code) on our board, but we had no time for it yet.

2022-05-13 15:11 UTC, mcalmer commented
@vzhestkov changed

2022-05-13 15:24 UTC, vzhestkov approved these changes
Thanks @mcalmer 
Looks good to me :+1:

2022-06-06 14:53 UTC, juliogonzalez requested changes

2022-06-06 14:53 UTC, juliogonzalez commented on susemanager/src/mgr_bootstrap_data.py
> +        'DEST' : DOCUMENT_ROOT + '/pub/repositories/slemicro/5//bootstrap/'
```suggestion
        'DEST' : DOCUMENT_ROOT + '/pub/repositories/slemicro/5/1/bootstrap/'
```

2022-06-06 15:06 UTC, juliogonzalez requested changes

2022-06-06 15:06 UTC, juliogonzalez commented on susemanager/src/mgr_bootstrap_data.py
> +        'PDID' : [2287], 'BETAPDID' : [1927], 'PKGLIST' : PKGLIST15_SALT + PKGLIST15_X86_ARM,
Are you sure you want `PKGLIST15_X86_ARM` here?

2022-06-06 15:06 UTC, juliogonzalez commented on susemanager/src/mgr_bootstrap_data.py
> +        'PDID' : [2283], 'BETAPDID' : [1928], 'PKGLIST' : PKGLIST15_SALT + PKGLIST15_X86_ARM,
Are you sure you want `PKGLIST15_X86_ARM` here?

2022-06-06 15:06 UTC, juliogonzalez commented on susemanager/src/mgr_bootstrap_data.py
> +        'PDID' : [2400], 'BETAPDID' : [1927], 'PKGLIST' : PKGLIST15_SALT + PKGLIST15_X86_ARM,
Are you sure you want `PKGLIST15_X86_ARM` here?

2022-06-06 15:06 UTC, juliogonzalez commented on susemanager/src/mgr_bootstrap_data.py
> +        'PDID' : [2401], 'BETAPDID' : [1928], 'PKGLIST' : PKGLIST15_SALT + PKGLIST15_X86_ARM,
Are you sure you want `PKGLIST15_X86_ARM` here?

2022-08-05 08:51 UTC, mcalmer commented
We think we do not need this as of now.

2022-08-05 08:51 UTC, closed without merging