Do not allow creating path if nonexistent user or group in fileutils
uyuni-project/uyuni pull request #5453
Opened 2022-05-17 07:57 UTC by ycedres

## What does this PR change?

Fixes the function `makedirs` in `uyuni.common.fileutils` that was creating the required path even if the specified user/group did not exist, and then failing to chown. Now it does not create the path and raises an exception.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed:  user invisible changes

- [X] **DONE**

## Test coverage
- No tests:  bugfix

- [X] **DONE**

## Links

Fixes #5106 
Tracks https://github.com/SUSE/spacewalk/issues/17730

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-05-18 10:20 UTC, vzhestkov approved these changes
Looks good :+1: 
Just one really nitpicky comment: maybe additionally `blacken` the modified python source file?

2022-05-18 12:06 UTC, agraul requested changes
Logic is fine, but I'm not sure if we can ship f-strings just yet. Maybe @meaksh can share his opinion on how to progress.

2022-05-18 12:06 UTC, agraul commented on python/uyuni/common/fileutils.py
> +        raise OSError(f"*** ERROR: user {user} doesn't exist. Cannot create path.")
Code in `uyuni.common` is used on both Uyuni server and the clients, not all of which use Python 3.6+. We need to check that only code that's exclusive to Uyuni server can hit this code path or wait until we're free to be incompatible with the Python interpreters on client systems.

SUMA 4.3 will be the last release that supports the traditional stack, after its release we can start introducing incompatibilities (on purpose).

2022-05-18 12:06 UTC, agraul commented on python/uyuni/common/fileutils.py
> +    """return uid, gid given user and group"""
Same as the other docstring.

2022-05-18 14:58 UTC, agraul commented
> Looks good +1 Just one really nitpicky comment: maybe additionally `blacken` the modified python source file?

IMO we shouldn't run `black` on individual files just yet. I think it's better to do it once for the whole project, in its own commit, at the same time we add the tooling into our CI and git hooks. I share Black's creator's [reasoning](https://lukasz.langa.pl/36380f86-6d28-4a55-962e-91c2c959db7a/) on this topic.

2022-07-25 12:14 UTC, ycedres commented
Successfully built in the CI (build 1464) but without running all scopes. Another build including the secondary tests has been run (1468).

2022-07-26 07:50 UTC, juliogonzalez commented
Since the branch freeze was on Friday, this a P3, and we have some failures on secondary, let's postpone merging this for the next version.

2022-08-22 10:01 UTC, merged