send notifications as email
uyuni-project/uyuni pull request #5512
Opened 2022-05-27 13:59 UTC by mcalmer

## What does this PR change?

The notifications shown in the WebUI are not so usefull for people who not login very often.
Send them also as email if email notifications in the user preferences is enabled.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-07-05 09:49 UTC, mcalmer commented
CI: https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1396/

2022-07-06 05:17 UTC, mcalmer commented
Missing: Notifications created from the python stack (Bootstrap repo generation) is entered directly into the DB and do not send an email.
Also "Channel Sync Failed" on reposync errors do not send mails. Need investigation

2022-07-06 08:57 UTC, lucidd approved these changes
besides what thomas already mentioned looks good.

2022-12-01 08:18 UTC, cbosdo requested changes
Spot a problem in the python code. It would also be nice to address the reported code smells or at least mark them as wontfix.
https://sonarcloud.io/project/issues?id=uyuni-project_uyuni&pullRequest=5512&resolved=false&types=CODE_SMELL

2022-12-01 08:18 UTC, cbosdo commented on python/uyuni/common/notificationUtils.py
> +        client.tasko.createBootstrapRepoFailedNotification(self.identifier, self.details)
Missing `return`  here

2022-12-02 08:18 UTC, mcalmer commented on python/uyuni/common/notificationUtils.py
> +        client.tasko.createBootstrapRepoFailedNotification(self.identifier, self.details)
fixed

2022-12-02 09:05 UTC, cbosdo approved these changes

2022-12-04 14:01 UTC, merged