addErrataUpdate API for multiple servers
uyuni-project/uyuni pull request #5592
Opened 2022-06-22 15:29 UTC by mbussolotto

## What does this PR change?

Create a new API endpoint for addErrataUpdate, that take multiple servers as argument. 
## GUI diff

No difference.

- [ ] **DONE**

## Documentation
API Doc
- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17895

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-07-04 08:39 UTC, mcalmer commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/chain/ActionChainHandler.java
> +                                    String chainLabel) {
Can we change the "single" version from line 269 to call this one ?
We have a lot of duplicate code.

2022-07-04 12:00 UTC, mcalmer requested changes
In the Handler we need both, the old and the new signature.
As `ActionChainManager` is internal, we can just change all the code which is calling it.
Seems that only the Handler and tests are calling it. So here it is ok, to just change it.

2022-07-04 13:32 UTC, mcalmer approved these changes
Looks good. Thanks

2022-07-04 14:45 UTC, mbussolotto commented
ci tests: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1392/

2022-07-05 07:20 UTC, mbussolotto commented
new CI tests: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1394/

2022-07-08 08:52 UTC, mbussolotto commented
another CI test: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1414/

2022-07-14 09:43 UTC, merged