Fixed missing "options" in args, for spacecmd/src/spacecmd/system.py
uyuni-project/uyuni pull request #5614
Opened 2022-06-29 05:31 UTC by slsnow

With the "options" value missing, `spacecmd -- system_listmigrationtargets` fails with "ERROR: too many values to unpack (expected 1)".
https://bugzilla.suse.com/show_bug.cgi?id=1201003

## What does this PR change?
- Fixes that command output.

- That command is necessary for this documented workflow to work properly:
https://github.com/uyuni-project/uyuni-docs/blob/master/modules/client-configuration/pages/client-upgrades-product-migration.adoc

## GUI diff
- No difference.

## Documentation
- No documentation needed: 

## Test
- Unsure about tests

## Links
- https://bugzilla.suse.com/show_bug.cgi?id=1201003

## Changelogs
- Not sure if changelog is needed

2022-07-11 07:53 UTC, mbussolotto commented
Fixes: https://github.com/SUSE/spacewalk/issues/18272

2022-07-18 11:05 UTC, mbussolotto commented
> Not sure if changelog is needed

Yes, they are always required. You should add a line on top of `spacecmd/spacecmd.changes` like:
```
- Fix missing argument on system_listmigrationtargets (bsc#1201003)
```
Then I think the PR can be approved

2022-07-19 07:18 UTC, slsnow reviewed
Added the requested changelog

2022-07-19 08:56 UTC, mbussolotto requested changes

2022-07-19 08:56 UTC, mbussolotto commented on spacecmd/spacecmd.changes
> +Tue July 19 09:20 AM CEST 2022 - ssnow@suse.com
Line 1 and 2 should be removed (they're added when the package is released). Line 3 and 4 are enough.

2022-07-19 08:58 UTC, mbussolotto commented on spacecmd/spacecmd.changes
> +Tue July 19 09:20 AM CEST 2022 - ssnow@suse.com
ok, I was able to make the change by myself :). Before merging, please wait python team or @meaksh review

2022-07-19 09:49 UTC, agraul approved these changes

2022-07-20 09:08 UTC, merged