Adding channels required in constants.rb
uyuni-project/uyuni pull request #5715
Opened 2022-07-27 07:16 UTC by elariekerboull

## What does this PR change?

Enabling additional channels in the testsuite required by the list of necessary channels to bootstrap minions.

## GUI diff

No difference.

Before:

After:

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- Cucumber tests were added : additional channels are selected for synchronization

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-08-19 09:01 UTC, Bischoff approved these changes
code looks good apart from And/When,

but how/when did you see this container module was needed?

2022-08-19 09:02 UTC, Bischoff requested changes

2022-08-19 09:02 UTC, Bischoff commented on testsuite/features/build_validation/reposync/srv_sync_all_products.feature
> +    And I open the sub-list of the product "Basesystem Module 15 SP1 x86_64"
When

2022-08-19 09:02 UTC, Bischoff commented on testsuite/features/build_validation/reposync/srv_sync_all_products.feature
> +    And I select "Containers Module 12 x86_64" as a product
When

2022-08-19 09:02 UTC, Bischoff commented on testsuite/features/build_validation/reposync/srv_sync_all_products.feature
> +    And I select "Containers Module 15 SP2 x86_64" as a product
When

2022-08-19 09:02 UTC, Bischoff commented on testsuite/features/build_validation/reposync/srv_sync_all_products.feature
> +    And I select "Containers Module 15 SP3 x86_64" as a product
When

2022-08-19 09:02 UTC, Bischoff commented on testsuite/features/build_validation/reposync/srv_sync_all_products.feature
> +    And I select "Containers Module 15 SP4 x86_64" as a product
When

2022-09-16 14:49 UTC, elariekerboull commented
Not relevant anymore.

2022-09-16 14:49 UTC, closed without merging