explicitly require java-11-openjdk
uyuni-project/uyuni pull request #5740
Opened 2022-08-04 10:20 UTC by mcalmer

## What does this PR change?

Prevent installing higher versions of java which might not work with SUMA/Uyuni

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/18535

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-08-05 09:25 UTC, juliogonzalez requested changes
As discussed yesterday, for now we changed the pattern and that fixes the issue.

We'll need to change more packages and not just `spacewalk-java`, but we also need to think if we want a different approach, because right now we have the Java version in several places, and we need to remember about all of them if we want to change the Java version.

To be discussed later.

@mcalmer not sure if you want a card for this.

2022-08-05 10:44 UTC, mcalmer commented
I think we close this PR as we decided for a different solution.
The java version change discussion may happen after summer. I would suggest to create an issue and put it into the planning board for discussion

2022-08-05 10:44 UTC, closed without merging

2022-08-08 10:43 UTC, juliogonzalez commented
@mcalmer can you create the issue?

2022-08-08 11:02 UTC, mcalmer commented
> @mcalmer can you create the issue?

Done https://github.com/SUSE/spacewalk/issues/18554