RHEL9 java enablement
uyuni-project/uyuni pull request #5945
Opened 2022-09-18 12:37 UTC by avshiliaev

## What does this PR change?

RHEL9 java enablement

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage

- Unit tests were added

- [ ] **DONE**

## Links

Implements https://github.com/SUSE/spacewalk/issues/18471

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-11-01 17:39 UTC, aaannz approved these changes
I am not sure if this is all what is needed also adding those thousands of sql data seems strange to me, but I guess this is how it was done.

So LGTM from me.

2022-11-01 19:37 UTC, mcalmer requested changes
Schema upgrade is missing

2022-11-05 10:49 UTC, mcalmer requested changes

2022-11-05 10:49 UTC, mcalmer commented on schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/001-rhnKSInstallType.sql
> +    );
Wrong schema migration directory. We are still at susemanager-schema-4.4.1 .
So the migration need to go into a directory with the name 

   susemanager-schema-4.4.1-to-susemanager-schema-4.4.2

I think this is also the reason for the schema migration test errors

2022-11-05 10:49 UTC, mcalmer commented on schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/002-rhnKickstartTimezome.sql
> +insert into rhnKickstartTimezone (id, label, name, install_type)
same as above - wrong schema migration directory

2022-11-07 14:56 UTC, mcalmer approved these changes
Looks good now. You only need to solve the conflict in the changes before you can merge.

2022-11-08 14:15 UTC, merged