Avoid concurrency issues during reporting database synchronization
uyuni-project/uyuni pull request #6075
Opened 2022-10-26 08:46 UTC by mackdk

## What does this PR change?

This PR ignores conflicts that may happen during the insert of the data into the reporting database. These conflicts can only occur if the data from the source tables changes. This modification may change how the extracted data is sorted and paginated, and thus causing the same row to be inserted twice. By ignoring the insert conflict, we prevent an hard failure during the synchronization process, at the cost of losing the newest data, which will be picked up by the following run of the sync task.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- Unit tests were added

- [X] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/18552

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2022-10-26 09:46 UTC, mcalmer requested changes

2022-10-26 09:46 UTC, mcalmer commented on java/spacewalk-java.changes
> +- Ignore insert conflicts during reporting database update
please add the bugnumber

2022-10-26 10:34 UTC, mackdk commented on java/spacewalk-java.changes
> +- Ignore insert conflicts during reporting database update
Fixed

2022-11-21 12:40 UTC, lucidd approved these changes

2022-11-21 12:40 UTC, lucidd approved these changes

2022-11-28 14:40 UTC, mackdk commented
@mcalmer could you please have a look at this PR again when you have the chance? I would like to merge it to master as well

2022-11-29 09:53 UTC, merged