Remove outdated advice from errata mail
uyuni-project/uyuni pull request #6410
Opened 2022-12-30 13:09 UTC by wweellddeerr

## What does this PR change?

It changes the header of errata notification email to not include outdated instructions.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/17829

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-01-02 10:10 UTC, admd approved these changes

2023-01-02 10:44 UTC, mcalmer requested changes

2023-01-02 10:44 UTC, mcalmer commented on java/code/src/com/redhat/rhn/frontend/strings/template/StringResource_en_US.xml
> -as root on the system in question to refresh your software profile.
I think not everything is obsolete. The first 2 sentence are still correct and important.

2023-01-04 16:08 UTC, mcalmer approved these changes

2023-01-05 12:51 UTC, merged