Use a profile coming from scap-security-guide
uyuni-project/uyuni pull request #6471
Opened 2023-01-16 11:40 UTC by orestis87

## What does this PR change?
Use a profile coming from scap-security-guide package instead of a profile coming from openscap-content, so to follow our internal documentation https://documentation.suse.com/suma/4.3/en/pdf/suse_manager_administration_guide.pdf page 147

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/20139
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-01-16 12:03 UTC, Bischoff approved these changes
lgtm

2023-01-16 13:29 UTC, nodeg approved these changes
As Eric already mentioned, please bump the copyright year and do not forget the ports if needed.

2023-01-16 14:35 UTC, srbarrios approved these changes

2023-01-20 14:00 UTC, Bischoff approved these changes
LGTM

2023-01-20 14:03 UTC, Bischoff requested changes

2023-01-20 14:03 UTC, Bischoff commented on testsuite/features/secondary/min_salt_openscap_audit.feature
> +    And I disable the repositories "tools_update_repo tools_pool_repo" on this "sle_minion"
it looks like this line comes from another branch

2023-01-20 14:38 UTC, nodeg approved these changes

2023-01-20 14:48 UTC, ktsamis approved these changes

2023-01-20 14:57 UTC, Bischoff approved these changes
LGTM. Thanks for the changes!

2023-01-20 15:27 UTC, merged