Adjust server salt error detection
uyuni-project/uyuni pull request #6490
Opened 2023-01-18 12:21 UTC by elariekerboull

## What does this PR change?

The salt error detection was faulty, this PR aims to correct the detection script and exclude the detection of an expected error caused by `min_salt_lock_packages.feature`
## GUI diff
No difference.
- [ ] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes
- [ ] **DONE**

## Test coverage
- No tests: already covered
- [ ] **DONE**

## Links
Fixes # https://github.com/SUSE/spacewalk/issues/19626
Tracks # 
4.2
4.3
- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-01-26 15:45 UTC, srbarrios commented on testsuite/features/step_definitions/common_steps.rb
> +  ignore_error = (count_failures == 1) && output.include?('remove lock') && !$build_validation
That kind of one-liners are not really readable.
No worries adding extra code lines, are free :D

2023-01-26 15:53 UTC, ktsamis commented on testsuite/features/step_definitions/common_steps.rb
> +  ignore_error = (count_failures == 1) && output.include?('remove lock') && !$build_validation
I think it would be better to break this down in multiple lines with an if statement. I have a doubt it will be a boolean here at the end.

2023-01-27 11:53 UTC, elariekerboull commented
The current issue happening with Rocky8 seems to be that the targeted parent channel (`RHEL8-Pool for x86_64`) does not get attributed the `rhel8-pool-x86_64`  label unless one of its sub-product (e.g. `RES-8-Updates for x86_64` ) has started syncing.
The sub-product sync does not need to be completed to have the label present.
This seems to be an odd behaviour, to see why that is.

2023-02-10 13:29 UTC, srbarrios approved these changes

2023-02-10 13:35 UTC, Bischoff requested changes
see comment

2023-02-10 13:35 UTC, Bischoff commented on testsuite/features/step_definitions/common_steps.rb
> +  end
bug: if for example `count_failures` is equal to 2, `ignore_error` variable will be undefined

also it light be a bit a bit more readable with `if count_failures.nonzero? and not ignore_error`

2023-02-15 09:27 UTC, Bischoff approved these changes

2023-02-15 09:58 UTC, merged