fix not showing details
uyuni-project/uyuni pull request #6720
Opened 2023-03-10 15:09 UTC by avshiliaev

## What does this PR change?

Fix the `spacecmd activationkey_details <key>` command showing the key details only in the debug mode with the `-d` flag set. 

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage
- No tests: already covered

- [ ] **DONE**

## Links

Fixes https://github.com/SUSE/spacewalk/issues/20615

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-03-13 19:12 UTC, mcalmer commented on spacecmd/src/spacecmd/activationkey.py
> +        logging.info(_N(entry))
Afaik we use just 'print' for the output.

2023-03-14 10:35 UTC, mbussolotto approved these changes

2023-03-14 10:37 UTC, mbussolotto commented
@avshiliaev , I had the changes suggested by @mcalmer  (changes will avoid `INFO` at the line beginning). It was not requested but for me the PR is approved :D . Feel free to merge it

2023-03-14 11:03 UTC, mbussolotto requested changes
failure in unit test, I'll have a look on it

2023-03-14 13:14 UTC, mbussolotto approved these changes

2023-03-14 14:58 UTC, agraul approved these changes

2023-03-14 15:00 UTC, merged