change the comments in spacecmd/src/spacecmd/utils.py to use docstring
uyuni-project/uyuni pull request #6752
Opened 2023-03-20 00:01 UTC by Rakielle

## What does this PR change?

**The PR   modified the spacecmd/src/spacecmd/utils.py file to use docstring comments instead of source comments**

## GUI diff

No difference.

Before:

After:

- [x] **DONE**

## Documentation
- No documentation needed: **This PR only works on the docstrings, no code was modified or added**
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: **This PR only works on the docstrings, no code was modified or added**
- No tests: already covered

- [x] **DONE**

## Links

Fixes #6006 

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-03-31 11:38 UTC, ycedres requested changes

2023-03-31 11:38 UTC, ycedres commented on spacecmd/src/spacecmd/utils.py
> +            pkg1 (dict): A dictionary
The `pkg1` and `pkg2` parameters are objects different from dictionaries. I think [this](https://github.com/uyuni-project/uyuni/blob/0366d51b3ab3286fd73c18f96d7080e39cefd8b7/java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java#L1284) is an example. However, you could just write that pkg1 is an object describing a package.

2023-03-31 11:38 UTC, ycedres commented on spacecmd/src/spacecmd/utils.py
> +            bool: Returns false if a key in options has value else returns true otherwise
You could add a bit of semantics for the description of returned value (in addition to its type), for example "returns false if named options were passed".

2023-03-31 11:38 UTC, ycedres commented on spacecmd/src/spacecmd/utils.py
> +
With the same idea of adding semantics to the parameters description, here we could say that `s` is the string that's going to be parsed as the type `type_to`.

2023-03-31 11:38 UTC, ycedres commented on spacecmd/src/spacecmd/utils.py
> +
Here maybe we could add the semantics of the parameters version, release and epoch  (instead of just writing the type).

2023-04-04 11:15 UTC, Rakielle commented on spacecmd/src/spacecmd/utils.py
> +            pkg (dict): pkg1 or pk2 If the objects are not the same, else returns none
The function returns one of pkg1, pkg2, or None. The function uses the returned value from `labelCompare` to decide which pkg to return. I modified the message though

2023-04-05 12:38 UTC, ycedres requested changes
Thanks for  the changes! I suggested some more changes to improve the docstring documentation of the module.

2023-04-05 12:38 UTC, ycedres commented on spacecmd/src/spacecmd/utils.py
> +            pkg2 (dict): An object describing a package
```suggestion
            pkg1 (dict): A dictionary describing a package
            pkg2 (dict): A dictionary describing a package
```

2023-04-10 16:12 UTC, ycedres approved these changes
Thank you very much for your contribution!

2023-04-10 16:12 UTC, merged