Add bootstrap repository definitions for SLE-Micro 5.4 and openSUSE Leap Micro 5.4
uyuni-project/uyuni pull request #6872
Opened 2023-04-13 17:03 UTC by mackdk

## What does this PR change?

Port of https://github.com/SUSE/spacewalk/pull/21108

This PR adds the bootstrap definitions for SLE-Micro 5.4 and for openSUSE Leap Micro 5.4

## Links

Fixes https://github.com/SUSE/spacewalk/issues/20739

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-04-14 09:02 UTC, mcalmer commented on susemanager/src/mgr_bootstrap_data.py
> +    },
This looks wrong here

2023-04-17 09:47 UTC, mackdk commented on susemanager/src/mgr_bootstrap_data.py
> +    },
Removed

2023-04-17 11:26 UTC, mcalmer approved these changes

2023-04-18 11:18 UTC, juliogonzalez commented
@mackdk I reopened the issue. Please do not close until this is merged.

2023-04-18 11:19 UTC, mackdk commented
> @mackdk I reopened the issue. Please do not close until this is merged.

Yes, thanks it was closed automatically when I merged on 4.3

2023-04-18 11:20 UTC, juliogonzalez commented
Title of this PR is wrong, because you are handling in a single PR the bootstrap repositories definitions and spacewalk-common-channels at the same time.

No need need to split the PR, but at least fix the title, and maybe the description.

2023-04-18 11:56 UTC, juliogonzalez commented
> > @mackdk I reopened the issue. Please do not close until this is merged.
> 
> Yes, thanks it was closed automatically when I merged on 4.3

Yup, that's a classic mistake (happens to me as well, from time to time).

When you are targeting more than one branch, avoid using `Fixes #NNNNN` :-)

2023-04-18 12:14 UTC, mackdk commented
> you are handling in a single PR the bootstrap repositories definitions and spacewalk-common-channels

I change the title but this is just for bootstrap repository for SLE Micro 5.4 and openSUSE Micro 5.4

2023-04-18 12:22 UTC, juliogonzalez commented
> > you are handling in a single PR the bootstrap repositories definitions and spacewalk-common-channels
> 
> I change the title but this is just for bootstrap repository for SLE Micro 5.4 and openSUSE Micro 5.4

Not really, you also have a comment with the message `Added openSUSE Leap Micro 5.4 to spacewalk-common-channels`?

2023-04-18 12:23 UTC, juliogonzalez commented
> > > you are handling in a single PR the bootstrap repositories definitions and spacewalk-common-channels
> > 
> > 
> > I change the title but this is just for bootstrap repository for SLE Micro 5.4 and openSUSE Micro 5.4
> 
> Not really, you also have a comment with the message `Added openSUSE Leap Micro 5.4 to spacewalk-common-channels`?

But at the same time the changes for `spacewalk-common-channels`are not in the diff? :-?

2023-04-18 12:24 UTC, juliogonzalez commented
> > > > you are handling in a single PR the bootstrap repositories definitions and spacewalk-common-channels
> > > 
> > > 
> > > I change the title but this is just for bootstrap repository for SLE Micro 5.4 and openSUSE Micro 5.4
> > 
> > 
> > Not really, you also have a comment with the message `Added openSUSE Leap Micro 5.4 to spacewalk-common-channels`?
> 
> But at the same time the changes for `spacewalk-common-channels`are not in the diff? :-?

I understand now. One of your commits is wrong. Both commits are about bootstrap repos.

2023-04-26 07:47 UTC, nodeg requested changes
It is written without the dash :wink:

2023-04-26 07:47 UTC, nodeg commented on susemanager/susemanager.changes
> +- Add bootstrap repository definitions for SLE-Micro 5.4
```suggestion
- Add bootstrap repository definitions for SLE Micro 5.4
```

2023-04-27 09:10 UTC, mackdk commented on susemanager/susemanager.changes
> +- Add bootstrap repository definitions for SLE-Micro 5.4
Fixed

2023-04-28 09:01 UTC, nodeg approved these changes

2023-05-08 08:42 UTC, merged