Add cucumber tests for recurring actions
uyuni-project/uyuni pull request #6933
Opened 2023-04-26 00:24 UTC by wweellddeerr

## What does this PR change?

Adjust recurring actions cucumber tests and add new scenarios for custom states

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- Cucumber tests were added

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-06-02 10:48 UTC, Bischoff requested changes
Thanks for this Welder

See my remarks here

https://github.com/SUSE/spacewalk/issues/21040#issuecomment-1573500529

2023-06-16 10:06 UTC, ktsamis approved these changes
To me it looks good but I still would like Eric to take a look. Thanks a lot for this Welder :)

2023-06-21 08:24 UTC, Bischoff requested changes
Thanks for the hard work, Welder.

Things I'd like to be changed:

1 - `Then` / `When` / `And` nitpicks (see details in this review)

2 - Some scenarios seem very long. Maybe it's possible to split them a bit?

3 - You now test that the events indeed appear as scheduled. That's a huge progress.
     But could we get further and test for real action results ? (file created, system setting changed, whatever)

4 - You are not testing the integration of custom actions (unless I missed it)


Thanks.

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see "Configure states to execute" text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    And I enter "custom_state_schedule_name" as "scheduleName"
When

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see "Schedule successfully created" text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see "Schedule 'custom_state_schedule_name_changed' has been deleted." text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
>      Then I wait until I see "Schedule successfully created" text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
>      Then I wait until I see "Schedule successfully updated" text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see the event "Apply recurring states [util.syncbeacons] scheduled by admin" completed during last minute, refreshing the page
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
>      Then I wait until I see "Schedule successfully created" text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see the event "Apply recurring states [hardware.profileupdate] scheduled by admin" completed during last minute, refreshing the page
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see "Schedule 'schedule_name_org' has been deleted." text
And

2023-06-21 08:24 UTC, Bischoff commented on testsuite/features/secondary/min_recurring_action.feature
> +    Then I wait until I see "Schedule 'schedule_name_minion' has been deleted." text
And

2023-06-22 08:07 UTC, jordimassaguerpla commented
Hi! Sorry there was an issue with podman. The issue is fixed in master. Could you please rebase your PR? Sorry for any inconvenience.

2023-06-23 13:04 UTC, Bischoff approved these changes
Looking very good, thanks!

Just a last nitpick: you create *a* xyz, but then you edit/view/delete *the* xyz. Could you please fix that in the scenario titles?

2023-06-23 22:35 UTC, merged