Minor Uyuni bugfixes
uyuni-project/uyuni pull request #6942
Opened 2023-04-26 16:55 UTC by cbbayburt

Fixes various minor bugs.

## Links

- Fixes https://github.com/SUSE/spacewalk/issues/21095

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-05-02 08:33 UTC, agraul requested changes
I only looked at the Python code and would prefer if we could be consistent with existing code that checks the availability of API endpoints.

2023-05-02 08:33 UTC, agraul commented on spacecmd/src/spacecmd/misc.py
From what I can see in other files, we don't use `try...except` to handle availability of API endpoints, could you adjust your code to use `hasattr()`?
For inspiration you could take a look at 
 https://github.com/uyuni-project/uyuni/blob/2c841115a1115ab441e030f58cc617373331ab6e/spacecmd/src/spacecmd/activationkey.py#L1681-L1683

2023-05-03 11:08 UTC, cbbayburt commented on spacecmd/src/spacecmd/misc.py
@agraul I don't understand how you can use `hasattr` to check the availability of an API endpoint. All the existing usages check for a spacecmd function, not an API endpoint.

The only alternative I can see is to make a call to SUMAs `api.getApiNamespaceCallList` to list all the endpoints and do a second call if `hasTraditionalSystems` exists. But that means pessimistically doing 2 calls every time, and since `spacecmd` is used mostly interactively, 2 sequential calls would have a noticeable delay so I wouldn't prefer that.

2023-05-03 11:42 UTC, agraul commented on spacecmd/src/spacecmd/misc.py
You're correct, existing uses of `hasattr` only check for spacecmd functions. I was confused about that. There is, however, one instance where `hasattr`'s "sibling" `getattr` is used: https://github.com/uyuni-project/uyuni/blob/2c841115a1115ab441e030f58cc617373331ab6e/spacecmd/src/spacecmd/api.py#L88

Looking at it more closely, that does not work as I expected. I thought it would check if the method is actually available, but it does not - it just calls `api()` and catches the exception like you do. I guess we don't have an XMLRPC server that supports introspection, otherwise we could use https://docs.python.org/3/library/xmlrpc.client.html#xmlrpc.client.ServerProxy.system.listMethods

2023-05-03 11:42 UTC, agraul approved these changes

2023-05-04 10:38 UTC, merged