Converting tuple to namedtuple for editor method - issue #6004
uyuni-project/uyuni pull request #6964
Opened 2023-05-01 11:50 UTC by amentee

## What does this PR change?

It converts tuple to namedtuple for editor method in spacecmd/src/spacecmd/utils.py file.

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-05-01 11:51 UTC, amentee commented
@agraul - Please review and let me know if this is good or needs some changes

2023-05-08 14:41 UTC, agraul requested changes
Thanks a lot for the pull request! I left two comments inline, please take a look when you have time.

The idea behind #6004 is to use named tuples everywhere in `spacecmd/src/` where currently tuples are returned, the `editor()` function is just an example to get you started. 

It would be great if you could check more usages where tuples are currently returned and come up with meaningful names for the fields.

2023-05-08 14:41 UTC, agraul commented on spacecmd/src/spacecmd/utils.py
> +            File = namedtuple("file", ("contents", "file_name"))
Normally, type declarations are done in the module scope. Is there a specific reason you've opted to have it inside the function?

2023-05-08 14:41 UTC, agraul commented on spacecmd/src/spacecmd/utils.py
>              return [], ''
I think this return statement should use the same type.

2023-09-18 08:11 UTC, Etheryte commented
@agraul Is this still relevant or should we close this as stale?

2023-09-18 14:46 UTC, agraul commented
> @agraul Is this still relevant or should we close this as stale?

Let's close it for now. @amentee if you want to continue working on this PR, please let us know.

2023-09-18 14:46 UTC, closed without merging