Add devel repo for each minion needed
uyuni-project/uyuni pull request #7154
Opened 2023-06-16 13:20 UTC by ktsamis

## What does this PR change?

Because we are missing devel repos in our activation keys and channels we are not currently testing the devel code in the CI. This PR attempts to fix that gap. We add devel repos for each os family as a custom repo in the fake channels we use in the activation keys.

This should not only fix the 4.2 failure for init buildhost but also cover a gap we have. We are currently testing our nightly builds in CI without devel repos (added in sumaform, disabled as soon as we bootstrap) because we only use the latest released from the SUMA server when we bootstrap. 

context: https://bugzilla.suse.com/show_bug.cgi?id=1212416
more context: https://suse.slack.com/archives/C02D12TNYLS/p1686915333705209

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- Cucumber tests were added

- [x] **DONE**

## Links

Fixes no issue, directly from testsuite review
Tracks 4.3: https://github.com/SUSE/spacewalk/pull/21794
4.2: https://github.com/SUSE/spacewalk/pull/21793

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-06-16 13:32 UTC, vandabarata commented on testsuite/features/step_definitions/command_steps.rb
> +end
```suggestion
end

```
missing new line

2023-06-16 13:47 UTC, ktsamis commented on testsuite/features/step_definitions/command_steps.rb
> +end
fixed

2023-09-11 06:53 UTC, nodeg commented
If you still want this, it should be rebased, @ktsamis.

2023-10-31 08:40 UTC, nodeg approved these changes

2023-10-31 08:41 UTC, nodeg approved these changes
LGTM. Do not forget to do a rebase!

2023-10-31 08:53 UTC, srbarrios requested changes
Hi Kostas.

On this PR, we are moving the responsibility of creating development repositories to our CI Testsuite, when this responsibility is for now given to Sumaform Salt states.

Sometime ago I was proposing to @Bischoff that exact move, but this will need to made as a big refactor where we need to align what it has been done by sumaform and what we do on CI testsuite.

This will also make the BV and CI testsuite similar, as we will be using custom channels/repositories in both of them.

But I strongly recommend that we postpone this change, and we do it with calm, consensus and well discussed.

For now, I think the best we can do is to keep using the injected repositories from sumaform, and use the steps we already have to enable and disable the repositories as soon as they become disabled by the onboarding, so as a last test after onboarding.

Also, we will need to assure that they are not disabled triggering other events like applying a salt high-state.

2024-02-01 17:27 UTC, ktsamis commented
I agree with Oscar, we need to discuss this more, and this PR is pretty old so it needs so much work it's better to start from scratch. I will close and we can revisit this later.

2024-02-01 17:27 UTC, closed without merging