throw and log SchedulerExceptions in taskomatic
uyuni-project/uyuni pull request #7311
Opened 2023-07-25 12:12 UTC by mcalmer

## What does this PR change?

In taskomatic we hide and ignore very often SchedulerExceptions. This lead into problems as some jobs might not be executed. Additionally `null` is returned in XMLRPC functions which is forbidden and cause exceptions.

This PR try to avoid returning `null` and throw SchedulerExceptions instead. It also improve logging of errors.

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-07-30 08:51 UTC, mcalmer commented
I run the on PR testsuite on it (https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2467/ )
and it showed no new errors. I also checked the logs and no SchedulerException appeared.
So I wonder why spacewalk was hiding this.

@cbbayburt @cbosdo any ideas?

2023-08-16 15:29 UTC, cbbayburt approved these changes

2023-08-16 15:35 UTC, cbbayburt commented
> I run the on PR testsuite on it (https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2467/ ) and it showed no new errors. I also checked the logs and no SchedulerException appeared. So I wonder why spacewalk was hiding this.
> 
> @cbbayburt @cbosdo any ideas?

the changes look good to me, but I don't understand what you mean by this?

2023-08-17 08:30 UTC, mcalmer commented
> > I run the on PR testsuite on it (https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2467/ ) and it showed no new errors. I also checked the logs and no SchedulerException appeared. So I wonder why spacewalk was hiding this.
> > @cbbayburt @cbosdo any ideas?
> 
> the changes look good to me, but I don't understand what you mean by this?

I was just asking if you maybe have an idea, why original spacewalk code ignored the exceptions instead of logging and throwing it.

2023-08-18 13:56 UTC, mackdk reviewed
LGTM, just some minor logging improvement to make the logs easier to read.

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoQuartzHelper.java
> +            log.error(e.getMessage(), e);
```suggestion
            log.error("Unable to remove scheduled trigger {}", trigger.getJobKey(), e);
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoQuartzHelper.java
> +            log.error(e.getMessage(), e);
```suggestion
            log.error("Unable to unschedule job {} of organization # {}", jobLabel, orgId, e);
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +            log.error(e.getMessage(), e);
```suggestion
        catch (SchedulerException | InvalidParamException e) {
            log.error("Unable to create job {}", schedule.getJobLabel(), e);
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +            log.error(e.getMessage(), e);
```suggestion
        catch (SchedulerException | InvalidParamException e) {
            log.error("Unable to create job {}", schedule.getJobLabel(), e);
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +            catch (Exception e) {
```suggestion
            catch (SchedulerException | InvalidParamException e) {
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +                log.error(e.getMessage(), e);
```suggestion
            catch (InvalidParamException | SchedulerException e) {
                log.error("Unable to create job {}", schedule.getJobLabel(), e);
```

2023-08-18 13:56 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +                log.error(e.getMessage(), e);
```suggestion
            catch (InvalidParamException | SchedulerException e) {
                log.error("Unable to reinitialize schedule for job {}", schedule.getJobLabel(), e);
            }
```

2023-08-18 15:18 UTC, mackdk requested changes
I was testing this change more with Welder and this PR (and my backport to 4.3) still needs work, in particular the changes to `scheduleRuns()`.

This API is in fact what we call to schedule actions on minions and it's meant to schedule multiple actions at a time. If we have an exception during the scheduling of one of those actions, we are now going to log the error but we are just not returning the scheduled date for it. This is still not handled on the caller side though. The result is that we have an action in `Queued` state that will never be executed (since no schedule was created for it) and will never change state. 

Thus we need to change the code that calls the api to schedule the actions to handle the possibility that the API rejects the scheduling due to an error.  In this case I think we have to mark the action as `Failed` or to remove it directly, notifying the error to the user. This possibly requires also a change on what we are returning from `scheduleRuns` as we need to associate the result of the scheduling with the action we passed as parameter. Now we are just returning a list of dates.

2023-08-21 09:17 UTC, cbosdo commented
> > > I run the on PR testsuite on it (https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/2467/ ) and it showed no new errors. I also checked the logs and no SchedulerException appeared. So I wonder why spacewalk was hiding this.
> > > @cbbayburt @cbosdo any ideas?
> > 
> > 
> > the changes look good to me, but I don't understand what you mean by this?
> 
> I was just asking if you maybe have an idea, why original spacewalk code ignored the exceptions instead of logging and throwing it.

Checking https://github.com/uyuni-project/uyuni/commit/04e63ecbae51 I don't know more than you. The comment doesn't help either and I had the impression to read StarOffice code again `Pech gehabt` 🙈

2023-08-21 10:02 UTC, mcalmer commented
@mackdk I have applied your suggestions

2023-08-21 10:46 UTC, mackdk commented on java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
> +            }
Seems like I doubled the curly brace with my suggestion, sorry :man_facepalming: 
```suggestion
```

2023-08-22 14:23 UTC, mackdk approved these changes
I'm working on a fix for the actions that remain queued in case of an error scheduling the taskomatic job to execute. 

Since this PR did not introduce this issue but just made it visible, I'm going to merge it so that we stop hiding the error if it happens.

2023-08-22 16:58 UTC, merged