Remove setup from the containerized server: moved to uyuniadm
uyuni-project/uyuni pull request #7331
Opened 2023-07-31 15:41 UTC by cbosdo

## What does this PR change?

Remove the setup for containerized server and the systemd service RPM as this is now done by uyuniadm.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: Not for `master` yet

- [X] **DONE**

## Test coverage
- No tests: tested with the E2E tests

- [X] **DONE**

## Links

Fixes #
Tracks # **add downstream PR, if any**

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-07-31 15:42 UTC, cbosdo commented
@uyuni-project/release-engineering you can remove yourself from this PR: not for master.

Note that the README still needs some love.

2023-07-31 16:21 UTC, mbussolotto approved these changes

2023-07-31 16:53 UTC, rjmateus approved these changes
Just one small note

2023-07-31 16:53 UTC, rjmateus commented on containers/doc/server-kubernetes/README.md
> +The migration procedure does not perform any hostname rename.
I think you should mention in here that we cannot perform an in-place migration, and a new machine is needed.

2023-08-01 12:41 UTC, deneb-alpha requested changes
Added some suggestions for fixing the case of:
* RKE2
* K3s
* Podman
* Kubernetes

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +The following assumes you have either a single-node rke2 or k3s cluster ready or a server with `podman` installed and enough resources for the Uyuni server.
```suggestion
The following assumes you have either a single-node RKE2 or K3s cluster ready or a server with `podman` installed and enough resources for the Uyuni server.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
>  Copy the `rke2-ingress-nginx-config.yaml` file to `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml` on your rke2 node.
```suggestion
Copy the `rke2-ingress-nginx-config.yaml` file to `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml` on your RKE2 node.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
>  Copy the `k3s-traefik-config.yaml` file to `/var/lib/rancher/k3s/server/manifests/` on your k3s node.
```suggestion
Copy the `k3s-traefik-config.yaml` file to `/var/lib/rancher/k3s/server/manifests/` on your K3s node.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +## For k3s
```suggestion
## For K3s
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +With k3s it is possible to preload the container images and avoid it to be fetched from a registry.
```suggestion
With K3s it is possible to preload the container images and avoid it to be fetched from a registry.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
>  Transfer the resulting `server-image.tar` to the k3s node and load it using the following command:
```suggestion
Transfer the resulting `server-image.tar` to the K3s node and load it using the following command:
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +In order to tell k3s to not pull the image, set the `pullPolicy` helm chart value to `Never` by passing a `--helm-value=values.yaml` parameter to `uyuniadm` with the following `values.yaml` file cont
```suggestion
In order to tell K3s to not pull the image, set the `pullPolicy` helm chart value to `Never` by passing a `--helm-value=values.yaml` parameter to `uyuniadm` with the following `values.yaml` file content:
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +## For rke2
```suggestion
## For RKE2
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +With k3s it is possible to preload the container images and avoid it to be fetched from a registry.
```suggestion
With K3s it is possible to preload the container images and avoid it to be fetched from a registry.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +## Notes for kubernetes
```suggestion
## Notes for Kubernetes
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +### For kubernetes
```suggestion
### For Kubernetes
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +When installing on a kubernetes cluster, it also assumes that `kubectl` and `helm` are installed on the server and configured to connect to the cluster.
```suggestion
When installing on a Kubernetes cluster, it also assumes that `kubectl` and `helm` are installed on the server and configured to connect to the cluster.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
>  Copy the `rke2-ingress-nginx-config.yaml` file to `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml` on your rke2 node.
```suggestion
Copy the `rke2-ingress-nginx-config.yaml` file to `/var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml` on your RKE2 node.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
>  Copy the `k3s-traefik-config.yaml` file to `/var/lib/rancher/k3s/server/manifests/` on your k3s node.
```suggestion
Copy the `k3s-traefik-config.yaml` file to `/var/lib/rancher/k3s/server/manifests/` on your K3s node.
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +## For podman
```suggestion
## For Podman
```

2023-08-01 12:41 UTC, deneb-alpha commented on containers/doc/server-kubernetes/README.md
> +### For podman
```suggestion
### For Podman
```

2023-08-02 08:27 UTC, merged