Fix recurring state execution not using correct order
uyuni-project/uyuni pull request #7507
Opened 2023-09-07 12:24 UTC by parlt91

## What does this PR change?

Using a Set instead of a list caused the order of the states to be incorrect.

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: Bugfix

- [x] **DONE**

## Test coverage

- No tests: Bugfix

- [x] **DONE**

## Links

Tracks https://github.com/SUSE/spacewalk/issues/22465

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2023-09-07 14:51 UTC, mcalmer requested changes
Please add a changelog with the bug number.
The code looks good. Not sure if you were able to test it?

2023-09-08 09:57 UTC, parlt91 commented
> Please add a changelog with the bug number. The code looks good. Not sure if you were able to test it?

Right. I thought there'd be no changelog needed, but I forgot that we have an open bug for it. I'll add one.
I also did some testing and the order seems to be fixed now (only did a couple runs, but the probability that it would randomly always have the defined order is pretty small, so I'm pretty confident it fixes the issue)

2023-09-08 10:03 UTC, mcalmer approved these changes

2023-09-08 10:04 UTC, mcalmer commented
Thanks. Don't forget to port it to 4.3 :-)

2023-09-08 11:26 UTC, merged