Move scripts added after tagging to next version
uyuni-project/uyuni pull request #7914
Opened 2023-11-20 11:23 UTC by witekest

The migration scripts in the directory `susemanager-schema-4.4.6-to-susemanager-schema-4.4.7` added after the tag `susemanager-schema-4.4.7-1` had been created should live in `susemanager-schema-4.4.7-to-susemanager-schema-4.4.8`.

2023-11-20 14:56 UTC, mcalmer requested changes
I think you need to repeat this on -to-4.4.9 .
As 4.4.8 is already released it will not be executed if somebody missed it.
We need to take care that it is executed on the next Update. This is not necessarily the version where it was really changed. We missed that point so we need to do it again on the next one.

2023-11-21 08:07 UTC, witekest commented
I moved now all the forgotten scripts to the new directory: `susemanager-schema-4.4.8-to-susemanager-schema-4.4.9`

2023-11-22 16:27 UTC, mcalmer approved these changes

2023-11-23 08:20 UTC, deneb-alpha approved these changes
LGTM, thanks

2023-11-23 08:58 UTC, merged