Improve Credentials hierarchy
uyuni-project/uyuni pull request #8032
Opened 2023-12-13 09:16 UTC by mackdk

## What does this PR change?

This PR refactors the Credentials class by introducing a hierarchy based on the credential type.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [X] **DONE**

## Test coverage
- Test updated, already covered.

- [X] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/22014
Ports(s): https://github.com/SUSE/spacewalk/pull/23066

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2023-12-19 09:10 UTC, mcalmer requested changes
some small nitpicks

2023-12-19 09:10 UTC, mcalmer commented on java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
> +        String sccDataPath = Config.get().getString(ContentSyncManager.RESOURCE_PATH, null);
ConfigDefaults got a new method "getOfflineMirrorDir()". Why is this not used here?

2023-12-21 09:27 UTC, srbarrios approved these changes
I did not review the whole PR.
But I'm fine with the need of restart taskomatic, after building the code, in our GH validation.

2023-12-21 09:40 UTC, mcalmer approved these changes

2023-12-21 09:56 UTC, parlt91 approved these changes
Frontend changes look good

2023-12-21 10:33 UTC, vzhestkov approved these changes
At least from the python point of view it makes things more simple. So I like it :+1:

2023-12-21 10:38 UTC, merged