PGDATA variable is unset, so pass the path with -D option
uyuni-project/uyuni pull request #8044
Opened 2023-12-15 11:35 UTC by mbussolotto

## What does this PR change?

PGDATA variable is unset, so pass the path with -D option

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed
- [x] **DONE**

## Test coverage
- No tests
- [x] **DONE**

## Links

Issue(s): #
Ports(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2023-12-15 11:36 UTC, mbussolotto commented
not sure if changelog are required or not

2023-12-15 11:38 UTC, mackdk approved these changes

2023-12-15 13:50 UTC, mcalmer approved these changes

2023-12-17 11:09 UTC, mcalmer commented
@mbussolotto seems this is not needed. We only need systemd in the container. Maybe it was there is the past because of dependencies, but now they changed them and it is not pulled in automatically anymore.

2023-12-17 11:13 UTC, mcalmer requested changes
maybe not needed

2023-12-18 08:40 UTC, closed without merging