Replace java 11 with java 17
uyuni-project/uyuni pull request #8055
Opened 2023-12-18 12:20 UTC by rjpmestre

## What does this PR change?

Update java 11 to 17

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage
- No tests: already covered

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/18554

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-01-09 17:42 UTC, cbosdo commented on java/spacewalk-java.spec
> +Version:        4.4.23
This should be only changed by release engineers

2024-01-09 17:42 UTC, cbosdo commented on .github/workflows/acceptance_tests_common.yml
> +  UYUNI_VERSION: um_master-upgrade_java_17
Don't forget to remove that chunk before merging

2024-01-09 17:42 UTC, cbosdo commented on spacewalk/setup/spacewalk-setup.spec
> +Version:        4.4.12
Shouldn't be changed in your PR

2024-01-09 17:42 UTC, cbosdo commented on susemanager/susemanager.spec
> +Version:        4.4.11
To be changed by release engineers only

2024-01-09 17:42 UTC, cbosdo commented on testsuite/dockerfiles/server-all-in-one/Dockerfile
> +RUN zypper ar -G http://download.opensuse.org/repositories/home:/RMestre:/branches:/systemsmanagement:/Uyuni:/Master/openSUSE_Leap_15.5/ uyuni_server_pool_repo_j17
Don't forget to remove before merging

2024-01-09 17:42 UTC, cbosdo commented on testsuite/podman_runner/07_start_server.sh
> +sudo -i podman run --rm --tmpfs /run -v ${src_dir}/schema/spacewalk/spacewalk-schema-upgrade:/usr/bin/spacewalk-schema-upgrade -v ${src_dir}/testsuite:/testsuite -v ${src_dir}/schema/spacewalk/upgrad
This change looks fishy

2024-01-09 17:42 UTC, cbosdo commented on testsuite/podman_runner/run
> +./18_run_secondary_tests.sh
This chunk shouldn't be in this PR

2024-03-27 08:45 UTC, cbosdo approved these changes

2024-03-27 10:34 UTC, Etheryte approved these changes
Nothing to review from frontend.

2024-03-27 10:38 UTC, m-czernek approved these changes
From Python side, not much to review :) IMO the test didn't need to change, but I don't mind it either way.

2024-03-27 13:55 UTC, cbosdo commented
> Nothing to review from frontend.

Now there is 😉

2024-03-27 14:17 UTC, Etheryte commented on web/html/src/manager/minion/packages/package-utils.ts
> +export const UNMANAGED: any = undefined;
I would recommend removing `any` here, that way we can actually see where this `undefined` can propagate and end up.

2024-03-27 14:17 UTC, Etheryte commented on web/html/src/manager/minion/packages/package-utils.ts
> +export function selectValue2PackageState(value: number): number {
This return type is not correct since it can also return `undefined`.

2024-03-27 14:18 UTC, Etheryte commented on web/html/src/manager/minion/packages/package-utils.ts
> +export function normalizePackageState(ps: number): number {
Same problem as the previous comment, this can also return `undefined`.

2024-03-27 14:19 UTC, Etheryte commented on web/html/src/manager/minion/packages/package.type.ts
> -export type OptionalValue = {
Looking at the rest of the code, it doesn't seem safe to me to remove this type and replace it with `number`. It seems we want `number | undefined` instead?

2024-03-27 14:46 UTC, cbosdo commented
> Would be nice to resolve the `number` vs `number | undefined` issue before merging this, otherwise we're creating a footgun.

I changed `OptionalValue` to an alias of `number | undefined`... let's see the test results but that should be the same thing

2024-03-27 17:11 UTC, Etheryte approved these changes

2024-03-28 09:06 UTC, Bischoff approved these changes
Approving the testsuite part (one-liner)

2024-03-28 09:07 UTC, ktsamis approved these changes
I'm not an expert in java unit test but looks good to me

2024-03-28 09:39 UTC, srbarrios approved these changes
LGTM.

I checked that the package is on the BCI:

```
 ~  podman ps --all
CONTAINER ID  IMAGE                                                                                 COMMAND               CREATED        STATUS                               PORTS       NAMES
4f46df5a6f11  registry.opensuse.org/systemsmanagement/uyuni/master/containers/uyuni/server:2024.02  /usr/lib/systemd/...  8 seconds ago  Created                                          cranky_moser
 ~  podman start cranky_moser
cranky_moser
 ~  podman exec -ti cranky_moser bash
===============================================================================
!
! This shell operates within a container environment, meaning that not all
! modifications will be permanently saved in volumes.
!
! Please exercise caution when making changes, as some alterations may not
! persist beyond the current session.
!
===============================================================================
4f46df5a6f11:/ # ls
_current_flavor  bin  boot  dev  etc  home  lib  lib64	mnt  opt  proc	remove_unused.sh  root	run  sbin  selinux  srv  sys  tmp  usr	var
4f46df5a6f11:/ # zypper ref
Retrieving repository 'Update repository of openSUSE Backports' metadata .........................................................................................................................................................[done]
Building repository 'Update repository of openSUSE Backports' cache ..............................................................................................................................................................[done]
Retrieving repository 'Non-OSS Repository' metadata ..............................................................................................................................................................................[done]
Building repository 'Non-OSS Repository' cache ...................................................................................................................................................................................[done]
Retrieving repository 'Open H.264 Codec (openSUSE Leap)' metadata ................................................................................................................................................................[done]
Building repository 'Open H.264 Codec (openSUSE Leap)' cache .....................................................................................................................................................................[done]
Retrieving repository 'Main Repository' metadata .................................................................................................................................................................................[done]
Building repository 'Main Repository' cache ......................................................................................................................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ....................................................................................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache .........................................................................................................................................[done]
Retrieving repository 'Main Update Repository' metadata ..........................................................................................................................................................................[done]
Building repository 'Main Update Repository' cache ...............................................................................................................................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata .....................................................................................................................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..........................................................................................................................................................................[done]
All repositories have been refreshed.
4f46df5a6f11:/ # zypper -n install java-17-openjdk-devel
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  java-17-openjdk java-17-openjdk-devel java-17-openjdk-headless

3 new packages to install.
Overall download size: 42.5 MiB. Already cached: 0 B. After the operation, additional 188.8 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: java-17-openjdk-headless-17.0.10.0-150400.3.39.2.aarch64 (Update repository with updates from SUSE Linux Enterprise 15)                                                                                 (1/3),  37.2 MiB    
Retrieving: java-17-openjdk-headless-17.0.10.0-150400.3.39.2.aarch64.rpm ............................................................................................................................................[done (13.0 MiB/s)]
Retrieving: java-17-openjdk-17.0.10.0-150400.3.39.2.aarch64 (Update repository with updates from SUSE Linux Enterprise 15)                                                                                          (2/3), 356.1 KiB    
Retrieving: java-17-openjdk-17.0.10.0-150400.3.39.2.aarch64.rpm ......................................................................................................................................................[done (1.7 MiB/s)]
Retrieving: java-17-openjdk-devel-17.0.10.0-150400.3.39.2.aarch64 (Update repository with updates from SUSE Linux Enterprise 15)                                                                                    (3/3),   4.9 MiB    
Retrieving: java-17-openjdk-devel-17.0.10.0-150400.3.39.2.aarch64.rpm ................................................................................................................................................[done (9.7 MiB/s)]

Checking for file conflicts: .....................................................................................................................................................................................................[done]
update-alternatives: using /usr/lib64/jvm/jre-17-openjdk/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/java.1.gz because associated file /usr/share/man/man1/java-java-17-openjdk.1.gz (of link group java) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/keytool.1.gz because associated file /usr/share/man/man1/keytool-java-17-openjdk.1.gz (of link group java) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/rmiregistry.1.gz because associated file /usr/share/man/man1/rmiregistry-java-17-openjdk.1.gz (of link group java) doesn't exist
update-alternatives: using /usr/lib64/jvm/jre-17-openjdk to provide /usr/lib64/jvm/jre-openjdk (jre_openjdk) in auto mode
update-alternatives: using /usr/lib64/jvm/jre-17-openjdk to provide /usr/lib64/jvm/jre-17 (jre_17) in auto mode
(1/3) Installing: java-17-openjdk-headless-17.0.10.0-150400.3.39.2.aarch64 .......................................................................................................................................................[done]
(2/3) Installing: java-17-openjdk-17.0.10.0-150400.3.39.2.aarch64 ................................................................................................................................................................[done]
update-alternatives: using /usr/lib64/jvm/java-17-openjdk/bin/javac to provide /usr/bin/jav [...]

2024-03-28 11:40 UTC, cbbayburt requested changes
I have a concern commented below, but I cannot suggest a perfect alternative. So let's maybe discuss this further.

2024-03-28 11:40 UTC, cbbayburt commented on java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
> +import static com.google.gson.internal.$Gson$Types.newParameterizedTypeWithOwner;
I'm not sure if it's a good idea to use methods from this package as it's obviously marked internal.

From `com.google.gson.internal` Javadoc:
> Do NOT use any class in this package as they are meant for internal use in Gson. These classes will very likely change incompatibly in future versions. You have been warned.

2024-03-28 11:40 UTC, cbbayburt commented on java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
> +        ParameterizedType parameterizedType = newParameterizedTypeWithOwner(null, ResultJson.class, type.getType());
Same concern as above, maybe we should create our own ParametrizedTypes like we do here:

https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/suse/scc/client/SCCClientUtils.java#L161-L180

It's verbose and kinda ugly, but I think it's safer this way.

2024-03-28 16:56 UTC, cbbayburt approved these changes

2024-03-28 19:29 UTC, merged