Fix the reference label in container images
uyuni-project/uyuni pull request #8144
Opened 2024-01-11 16:11 UTC by cbosdo

## What does this PR change?

The reference label value needs to match the build tag and then contain the product version.

The ARG PRODUCT_VERSION is appended when pushing the image to OBS.

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-01-11 16:24 UTC, deneb-alpha requested changes
I left a few comments

2024-01-11 16:24 UTC, deneb-alpha commented on containers/hub-xmlrpc-api-image/Dockerfile
> +LABEL org.opensuse.reference="${REFERENCE_PREFIX}/hub-xmlrpc-api:${PRODUCT_VERSION}.%RELEASE%"
I can't directly add a suggestion on the right line, but for tagging I also need one more  lable that is missing  in this Dockerfile
```suggestion
LABEL org.opensuse.reference="${REFERENCE_PREFIX}/hub-xmlrpc-api:${PRODUCT_VERSION}.%RELEASE%"
LABEL org.opencontainers.image.name=hub-xmlrpc-api-image
```

2024-01-11 16:24 UTC, deneb-alpha commented on containers/hub-xmlrpc-api-image/hub-xmlrpc-api.changes.cbosdonnat.versions-fix
> +- Use product version in reference label
```suggestion
- Use product version in reference label
- Add missing image name label
```

2024-01-11 16:27 UTC, cbosdo commented
> I left a few comments

Fixed! thanks

2024-01-11 16:28 UTC, deneb-alpha approved these changes
thanks,  LGTM  now

2024-01-11 19:27 UTC, deneb-alpha commented
@cbosdo there's one extra image on Head that is missing here `server-migration-14-16-image`. I'm adding a note here because I don't know if we need  to release it with 5.0 or no

2024-01-12 08:28 UTC, cbosdo commented
> @cbosdo there's one extra image on Head that is missing here `server-migration-14-16-image`. I'm adding a note here because I don't know if we need to release it with 5.0 or no

Fixed: we definitely need it

2024-01-12 08:30 UTC, deneb-alpha commented
> > @cbosdo there's one extra image on Head that is missing here `server-migration-14-16-image`. I'm adding a note here because I don't know if we need to release it with 5.0 or no
> 
> Fixed: we definitely need it

I closed my PR  in favor of this

2024-01-12 08:34 UTC, deneb-alpha requested changes
left a comment

2024-01-12 08:34 UTC, deneb-alpha commented on containers/server-migration-14-16-image/.cbosdonnat.versions-fix
I think this is wrong. mkchlog created it in this way because of the missing main .changes file

2024-01-12 08:34 UTC, deneb-alpha commented on containers/server-migration-14-16-image/server-migration-14-16-image.changes
not 100% sure if we can leave this empty or if tito can just create it when tagging for the first time.

2024-01-12 08:38 UTC, cbosdo commented on containers/server-migration-14-16-image/server-migration-14-16-image.changes
`tito` fails if that file is missing, but is happy if it's empty

2024-01-12 08:45 UTC, deneb-alpha approved these changes
LGTM,  thanks

2024-01-12 09:17 UTC, avshiliaev approved these changes
Thank you, Cedric! :rocket:

2024-01-12 10:06 UTC, merged