Add getRelevantErrata endpoint that takes a list of sids
uyuni-project/uyuni pull request #8203
Opened 2024-01-24 08:33 UTC by dottorblaster

## What does this PR change?

Solves (at least I hope so) #8183.

Adds a new endpoint to the API that lets `getRelevantErrata` have a list of `sid`s as a parameter. 

## GUI diff

No difference.

Before:

After:

- [X] **DONE**

## Documentation
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- I hope I got it right!

- [X] **DONE**

## Test coverage
- Unit tests were added

- [X] **DONE**

## Links

Issue(s): #8183 

- [X] **DONE**

## Changelogs

I still need to write an entry.

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-01-24 15:38 UTC, rjmateus approved these changes
Thank you for the contribution. Looks good to me but lets wait for Can review also.

2024-01-24 15:39 UTC, dottorblaster commented
Thank you so much @rjmateus! I'm fixing the changelog as well as soon as this build finished with satisfying results on my end :smile:

2024-01-25 10:38 UTC, cbbayburt requested changes
Thanks for the contribution, @dottorblaster.

I just requested some minor updates for the documentation to reflect the change. FYI, that the actual API documentation is generated from the javadoc entries that start with `@apidoc.`

2024-01-25 10:38 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
> +     * Returns a list of all errata that are relevant to the system.
```suggestion
     * Returns a list of all errata that are relevant to a list of systems.
```

2024-01-25 10:38 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
> +     * @apidoc.doc Returns a list of all errata that are relevant to the system.
```suggestion
     * @apidoc.doc Returns a list of all errata that are relevant to a list of systems.
```

2024-01-25 10:38 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
> +     * sid cannot be found.
```suggestion
     * @throws FaultException A FaultException is thrown if any server in the list cannot be found.
```

2024-01-25 10:38 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
> +     * @return Returns an array of maps representing the errata that can be applied
```suggestion
     * @return Returns an array of maps representing the errata that can be applied to each system
```

2024-01-25 11:00 UTC, cbbayburt approved these changes

2024-01-26 09:47 UTC, merged