QE: add systems errata API testing feature
uyuni-project/uyuni pull request #8332
Opened 2024-02-19 12:09 UTC by NamelessOne91

## What does this PR change?

Closes https://github.com/SUSE/spacewalk/issues/23534

Adds namespaces and testsuite support for  the system.getRelevantErrata API calls/endpoints and features to test them.

## GUI diff

No difference.

- [x] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage

- Cucumber tests and files were added and edited

- [x] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/23534
Port(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23773

- [x] **DONE**

## Changelogs

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2024-02-20 15:42 UTC, jordimassaguerpla commented
Hi ! We fixed a spelling mistake in the name of the tests and you will have to rebase your PR for the correct tests to run. Sorry for the inconvenience.

2024-02-22 11:15 UTC, Bischoff approved these changes

2024-02-22 11:15 UTC, ktsamis approved these changes
Looks good

2024-02-22 12:02 UTC, nodeg requested changes
It would make sense to add more labels. Otherwise, the scenarios will fail if the checked minions are not defined and used.

2024-02-22 13:08 UTC, NamelessOne91 commented on testsuite/features/secondary/srv_errata_api.feature
> +  Scenario: Check the relevant errata for multiple systems
Good point about having these labels, thanks

2024-02-22 13:19 UTC, NamelessOne91 commented on testsuite/features/support/http_client.rb
> +Faraday::Utils.default_params_encoder = Faraday::FlatParamsEncoder
It should not impact the other HTTP requests being done by the testsuite.
It instruct the encoder to not use  the parsing logic  for nested structures, like JSON or XML, which is probably the cause for the `sids` key being updated.
We are explicit on calling `to_json` on the params that are going to form the body a POST request.

Still, it is possible to set the parameters encoder at the individual HTTP request level.
So we can have it for GET requests only and leave the POST ones untouched.

2024-02-22 16:17 UTC, nodeg approved these changes

2024-02-22 16:20 UTC, merged