Add ids on the bootstrap errors modal textareas
uyuni-project/uyuni pull request #8500
Opened 2024-03-22 16:03 UTC by cbosdo

## What does this PR change?

In order to disambiguate which textarea to look for in the testsuite we need to add ids and use them in the tests.

## GUI diff

No difference.

- [X] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes
- [X] **DONE**

## Test coverage
- Cucumber tests were fixed

- [X] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [X] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-03-22 21:24 UTC, Etheryte requested changes
It would be preferable to use `data-testid` rather than `id`, that makes it explicit that these values are used by tests and are not just leftover. Right now if you check regular code for uses of these ids they will look unused and so look safe to remove.

2024-03-23 11:24 UTC, Bischoff approved these changes

2024-03-25 14:50 UTC, cbosdo commented
Tested and working

2024-03-25 14:50 UTC, Etheryte approved these changes
Looks good. 👍

2024-03-25 15:24 UTC, Bischoff approved these changes

2024-03-25 16:28 UTC, merged