fix pam configuration on SLES15SP6
uyuni-project/uyuni pull request #8648
Opened 2024-04-23 11:18 UTC by mbussolotto

## What does this PR change?

fix pam configuration on SLES15SP6

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-04-23 11:33 UTC, cbosdo commented on containers/server-image/Dockerfile
> -    authselect
couldn't you add those two packages to the EXTRA_PACKAGES argument as default value?

2024-04-23 11:45 UTC, cbosdo approved these changes

2024-04-23 11:49 UTC, mbussolotto commented
Testing in my OBS project before merging it

2024-04-23 13:20 UTC, cbosdo requested changes
Don't forget to merge your commits in one

2024-04-23 13:20 UTC, cbosdo commented on containers/server-image/Dockerfile
> +ARG EXTRAPACKAGES=shim nss-pam-ldapd authselect
don't add `shim` here as this is depending on the architecture we build on

2024-04-23 16:34 UTC, cbosdo commented on containers/server-image/Dockerfile
> +ARG EXTRAPACKAGES=shim%20nss-pam-ldapd
```suggestion
ARG EXTRAPACKAGES=nss-pam-ldapd
```
`shim` should not be in the defaults: it is only for some architectures

2024-04-24 09:07 UTC, cbosdo approved these changes

2024-04-24 09:46 UTC, deneb-alpha requested changes
the subpackages of https://smelt.suse.de/maintained/?q=sssd&with_debug=1 are all there, not everything is already in Micro 5.5 but this isn't a problem for us to build the  image. I think we are good to  go  in this way.

I left a suggestion for the .changes

2024-04-24 09:46 UTC, deneb-alpha commented on containers/server-image/Dockerfile
> +    sssd-ad \
I see it available https://smelt.suse.de/maintained/?q=sssd-ad&with_debug=1

2024-04-24 09:46 UTC, deneb-alpha commented on containers/server-image/Dockerfile
> +    sssd-ipa \
this too https://smelt.suse.de/maintained/?q=sssd-ipa&with_debug=1

2024-04-24 09:46 UTC, deneb-alpha commented on containers/server-image/Dockerfile
> +    sssd-krb5 \
same https://smelt.suse.de/maintained/?q=sssd-krb5&with_debug=1

2024-04-24 09:46 UTC, deneb-alpha commented on containers/server-image/Dockerfile
> +    sssd-tools
same https://smelt.suse.de/maintained/?q=sssd-tools&with_debug=1

2024-04-24 09:46 UTC, deneb-alpha commented on containers/server-image/server-image.changes.mbussolotto.pam_package
> +- fix PAM authentication using bci image
```suggestion
- Fix PAM authentication using BCI image
```

2024-04-24 11:46 UTC, cbosdo approved these changes

2024-04-24 11:52 UTC, deneb-alpha approved these changes
LGTM,thanks

2024-04-24 14:00 UTC, merged