Added api calls for notifications
uyuni-project/uyuni pull request #8668
Opened 2024-04-26 08:58 UTC by quinilo

## What does this PR change?

Added api calls getNotifications, makeNotificationRead, makeAllNotificationsRead, deleteNotification to UserHandler

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- Api documentation added

- [x] **DONE**

## Test coverage
- No tests: already covered

- [x] **DONE**

## Links

Issue(s): [#5540](https://github.com/uyuni-project/uyuni/issues/5540)

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-04-26 10:21 UTC, mcalmer commented
@quinilo Thanks. Sorry that I cannot be in the office today.

2024-04-26 10:40 UTC, cbbayburt requested changes
Hi @quinilo, thank you very much for the additions to the API.

I've suggested some changes below. Apart from those, here's another suggestion:

The `user` namespace is already a big one. Your changes introduce notifications as a new entity to the namespace. I think in this case, creating a new `user.notifications` namespace would help organize everything better. To do this, you need to do the following:
 - Create a new `UserNotificationsHandler` and move your endpoint methods there
 - Register your handler in the `HandlerFactory` class

And finally, some general remarks about the PR itself:

 - Please address the failing checks
 - Rebase the PR on top of `master` and squash your commits so only the relevant code changes are there
 - Some files are missing newlines at the end

About the documentation: I suggested some changes but I didn't build the docs myself so I might be missing something. To make sure the docs are generated correctly, please make sure to read the [wiki about writing documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) to build and validate your additions to the docs.

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
> +    public int makeNotificationRead(User user, UserNotification notification) {
I think having just the ID as input would be easier to use (considering both XMLRPC and HTTP)

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
> +    public int makeNotificationRead(User user, UserNotification notification) {
Also, accepting a collection of notifications instead of a single one would cover more cases.

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/UserNotificationSerializer.java
> +                .add("messageId", src.getMessage().getId())
`messageId` does not belong to the "User" domain and it has no use for the user, so I think we can leave it out (also from the javadoc above).

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
> +     * @apidoc.returntype #return_notifications()
You must tell the API docs generator to print out the structure of your serializer like in this example:

https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java#L109-L112

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/UserNotificationSerializer.java
> + *      #prop_array("date", "created")
```suggestion
 *      #prop("int", "id")
 *      #prop("int", "messageId")
 *      #prop("boolean", "read")
 *      #prop("string", "message")
 *      #prop("string", "type")
 *      #prop($date, "created")
```

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/UserNotificationSerializer.java
> + *ff
```suggestion
```

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
> +     * @apidoc.doc Makes a notification raed
`@apidoc.param #session_key()` is missing

2024-04-26 10:40 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
> +     * @apidoc.doc Deletes multiple notifications
`@apidoc.param #session_key()` is missing

2024-04-26 11:54 UTC, quinilo commented
@cbbayburt thanks for your review. I will fix the code

2024-05-20 13:23 UTC, mcalmer commented
@quinilo there are some checkstyle issues. Check the Details link to see what is wrong.

2024-05-20 15:24 UTC, quinilo commented
> @quinilo there are some checkstyle issues. Check the Details link to see what is wrong.

Do i have to write a changelog for this change?

2024-05-20 17:43 UTC, mcalmer commented
> > @quinilo there are some checkstyle issues. Check the Details link to see what is wrong.
> 
> Do i have to write a changelog for this change?

Yes, please do so. Thanks

2024-05-21 16:45 UTC, quinilo commented
> > > @quinilo there are some checkstyle issues. Check the Details link to see what is wrong.
> > 
> > 
> > Do i have to write a changelog for this change?
> 
> Yes, please do so. Thanks

In which file do I have to write the changelogs in this case?

2024-05-22 11:56 UTC, mcalmer commented
> In which file do I have to write the changelogs in this case?

https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog-rules-for-packages-in-git

There is a description about `mkchlog` and where the repo is to install it.
In the end it create a new file `spacewalk-java.changes.login.branch-name` and you write a line starting with a dash.

2024-06-03 11:34 UTC, closed without merging

2024-06-03 11:43 UTC, mcalmer commented
@quinilo sorry while fixing some problems I pushed incomplete content to your branch. I have opened everything again in the Uyuni git diretcly at https://github.com/uyuni-project/uyuni/pull/8860 .

2024-06-05 18:19 UTC, mcalmer commented
No, not for now.
I will give it a try and when master gets unlocked i will merge it. 
Thanks for this contribution