Quinilo Notification API
uyuni-project/uyuni pull request #8860
Opened 2024-06-03 11:41 UTC by mcalmer

## What does this PR change?

Added api calls getNotifications, makeNotificationRead, makeAllNotificationsRead, deleteNotification to UserNotificationHandler

Successor of https://github.com/uyuni-project/uyuni/pull/8668

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.

- [x] **DONE**

## Test coverage
- Unit tests were added

- [x] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni/issues/5540

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-06-22 10:01 UTC, mcalmer commented
I have fixed the last minor problems. Can be merged when master branch gets unlocked

2024-06-24 10:45 UTC, cbbayburt requested changes
Overall LGTM.

I commented some quick fixes for the documentation.

2024-06-24 10:45 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java
> +     * @apidoc.param #param_desc("boolean", "unread", "Read notifications.")
```suggestion
     * @apidoc.param #param_desc("boolean", "unread", "If true, return only unread notifications.")
```

2024-06-24 10:45 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java
> +     * @apidoc.param #param_desc("Collection", "notifications", "The target notification.")
```suggestion
     * @apidoc.param #array_single_desc("int", "notifications", "The list of notification IDs to set as 'read'.")
```

2024-06-24 10:45 UTC, cbbayburt commented on java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java
> +     * @apidoc.param #param_desc("collection", "notifications", "List of notification ids.")
```suggestion
     * @apidoc.param #array_single_desc("int", "notifications", "The list of notification IDs to delete.")
```

2024-07-22 11:45 UTC, merged