BV 5.0 GMC - Add SLE 15 SP6 to the resposync testsuite
uyuni-project/uyuni pull request #8932
Opened 2024-06-17 08:59 UTC by szachovy

## What does this PR change?

SLE 15 SP6 constants and timeouts with Leap 15.6

## GUI diff

No difference.

- [ ] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage
- No tests: already covered

- [ ] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/24568
Port(s): https://github.com/SUSE/spacewalk/pull/24577

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-06-17 09:47 UTC, Bischoff submitted a review, later dismissed
lgtm, but unchecked so far

2024-06-17 09:50 UTC, nodeg commented
Hm, it seems that https://github.com/uyuni-project/uyuni/pull/8723 was not complete.

2024-06-17 09:51 UTC, nodeg commented
@szachovy Could you also please to the backport to 4.3?

2024-06-17 09:59 UTC, szachovy commented
> @szachovy Could you also please to the backport to 4.3?

Yes, we are verifying it. Creating backport soon.

2024-06-17 12:50 UTC, Bischoff submitted a review, later dismissed
tested to work on 5.0 GMC automated BV

not tested on uyuni automated BV, but "looks" ok

2024-06-17 12:54 UTC, nodeg commented
## Uyuni

### Product

![image](https://github.com/uyuni-project/uyuni/assets/12104291/7a04b264-6455-4bf0-ac36-1d2e8503f971)
![image](https://github.com/uyuni-project/uyuni/assets/12104291/ab32d2f8-894f-4802-ad73-58fbe6726010)
![image](https://github.com/uyuni-project/uyuni/assets/12104291/59d964e2-7f6c-4b66-acce-b361b192b317)

### Client Tools
```bash
uyuni-server:/ # spacewalk-common-channels -l | grep sp6
(...)
 sles15-sp6-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
 sles15-sp6-uyuni-client: x86_64, s390x, aarch64, ppc64le
```

2024-06-17 14:03 UTC, szachovy commented
> ## Uyuni
> ### Product
> ![image](https://private-user-images.githubusercontent.com/12104291/340311381-7a04b264-6455-4bf0-ac36-1d2e8503f971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzE2OTksIm5iZiI6MTcxODYzMTM5OSwicGF0aCI6Ii8xMjEwNDI5MS8zNDAzMTEzODEtN2EwNGIyNjQtNjQ1NS00YmYwLWFjMzYtMWQyZTg1MDNmOTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTk0ZGI0ZGYzNDgyY2NkZDliNDI1NjZmYjE4MjJiMjkxMzU2YjgzZjJlZjQyOTkzYzQ2ZmRmN2Y1N2Y3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Tzn8bLxDJIglP2hG_3JTJuoqHqWSs57W6G3ekJVf6k) ![image](https://private-user-images.githubusercontent.com/12104291/340311444-ab32d2f8-894f-4802-ad73-58fbe6726010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzE2OTksIm5iZiI6MTcxODYzMTM5OSwicGF0aCI6Ii8xMjEwNDI5MS8zNDAzMTE0NDQtYWIzMmQyZjgtODk0Zi00ODAyLWFkNzMtNThmYmU2NzI2MDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMTE3MjczMzYwYWJhMzc1MmQyNjUyODg2MjI3MjRjZDYwODAwNDA3OTZmNzIzMzBmODU4YjU5Yzg5ZGZjN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOqYVmxVP4Ni227keDu8Go8N45n-vnNq-6Wo1xKHXvE) ![image](https://private-user-images.githubusercontent.com/12104291/340311474-59d964e2-7f6c-4b66-acce-b361b192b317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzE2OTksIm5iZiI6MTcxODYzMTM5OSwicGF0aCI6Ii8xMjEwNDI5MS8zNDAzMTE0NzQtNTlkOTY0ZTItN2Y2Yy00YjY2LWFjY2UtYjM2MWIxOTJiMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEzMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzQ5NzQ5OTU4YzBiOWFlZmM0OGI0YmI2MGMxYjVjZjQ2YjA2YzA0NDRkOTk4NmQyZjhmY2I4YjBlZWVlZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PX7unAoEqC2EtpdAhM0vwFssvUgfqha7iiZFeTBlCfI)
> 
> ### Client Tools
> ```shell
> uyuni-server:/ # spacewalk-common-channels -l | grep sp6
> (...)
>  sles15-sp6-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
>  sles15-sp6-uyuni-client: x86_64, s390x, aarch64, ppc64le
> ```
> 
> We already have them in the reposync files:
> 
> https://github.com/uyuni-project/uyuni/blob/65e6c03cee4e678ef31e01cea930348039c79f67/testsuite/features/build_validation/reposync/srv_sync_all_products.feature#L210-L214

Are the present channels sufficient, or are the ones I added underlying to them? I don't know what to do with Uyuni. If it requires more verification, can you please point me to an environment with an SP6 minion (I couldn't perform it from suma-06)? If you feel this change doesn't make sense for Uyuni, I will discard it now.

2024-06-17 14:15 UTC, nodeg commented
> If it requires more verification, can you please point me to an environment with an SP6 minion (I couldn't perform it from suma-06)

You can always take a look at the Uyuni (Podman) CI and see the channel names there.

>If you feel this change doesn't make sense for Uyuni, I will discard it now.

Either you discard them, or you take a look at an Uyuni environment and fix them. As you wish and as time permits. I would suggest discarding them, create a card for it and add it once we do not have that much pressure for 5.0.

2024-06-18 08:45 UTC, Bischoff requested changes
Remove second commit - even if this code is untested, it's necessarily less wrong with it than without it.

2024-06-18 09:07 UTC, Bischoff approved these changes
lgtm

2024-06-18 10:51 UTC, srbarrios approved these changes

2024-06-19 08:50 UTC, merged