Do not install spacewalk-utils-extra on server image
uyuni-project/uyuni pull request #9143
Opened 2024-08-06 15:15 UTC by rjmateus

## What does this PR change?

Do not install the spacewalk-utils-extra on the server image. At the same time move the taskotop tool to the spacewalk-utils package.

Next step would be remove the package `spacewalk-utils-extra`

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

Need port to 5.0 branch when it's ready.

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-08-06 15:23 UTC, mcalmer commented on containers/server-image/Dockerfile
> -    spacewalk-utils-extras \
I think there is also a changelog here in server-image

2024-08-06 15:24 UTC, mcalmer requested changes

2024-08-06 15:24 UTC, mcalmer commented on utils/spacewalk-utils.changes.rmateus.Manager-4.3
> +- move takotop tool to spacewalk-utils package
```suggestion
- move taskotop tool to spacewalk-utils package
```

2024-08-07 09:38 UTC, rjmateus commented
I have tested the PR using the Hexagon project in IBS, and it worked as expected. `spacewalk-utils-extra` was not installed and the tool taskotop was installed as part of `spacewalk-utils`

2024-10-25 14:41 UTC, rjmateus commented
lets not do it for now, and we must check each individually tool based on this page: https://confluence.suse.com/display/~RDiasMateus/SUMA+cmd+tools

2024-10-25 14:41 UTC, closed without merging