WIP: VSCode workspace usage demo
uyuni-project/uyuni pull request #9252
Opened 2024-09-06 14:49 UTC by Etheryte

## What does this PR change?

This is a demo of how to use VSCode workspace files so we can both have default configs and also the ability to change, override, etc.  

Please feel free to try it out and let me know if there's any use case this doesn't cover or anything that's missing. If we find that this doesn't work well or is too cumbersome, we can always try and find a different solution.  

Also, @Serp1co please review what you'd like to see in `settings.json` from the Java side, for now I just used what you pasted on Slack as testing values.

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-09-06 14:51 UTC, Etheryte commented
FYI: For the time being I didn't go removing anything from the already existing sub folder configs. Open to ideas if and or what we want to keep or remove on that front, or any alternative suggestions.

2024-09-11 13:50 UTC, Serp1co requested changes

2024-09-11 13:50 UTC, Serp1co commented on .vscode/settings.json
LGTM, but we also need to add the checkstyle properties:

    "java.checkstyle.properties": {
        "checkstyle.cache.file": "${workspaceFolder}/java/build/checkstyle.cache.src",
        "checkstyle.header.file": "${workspaceFolder}/java/buildconf/LICENSE.txt",
        "checkstyle.suppressions.file": "${workspaceFolder}/java/buildconf/checkstyle-suppressions.xml",
        "javadoc.lazy": "false",
        "javadoc.method.scope": "public",
        "javadoc.type.scope": "package",
        "javadoc.var.scope": "package"
    }

2024-09-11 16:02 UTC, Etheryte commented on .vscode/settings.json
Thanks, added.

2024-09-11 19:12 UTC, Serp1co approved these changes

2024-10-23 08:57 UTC, merged