Uyuni Health Check Tool Disconnected Solution
uyuni-project/uyuni pull request #9322
Opened 2024-10-04 08:28 UTC by ycedres

# DRAFT

## What does this PR change?

Initial implementation of the **Disconnected solution**. No access to an Uyuni server or existing monitoring stack, only access to a supportconfig.

See: https://github.com/uyuni-project/uyuni-rfc/blob/master/accepted/00101-health-check-tool.md

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-12-10 12:53 UTC, agraul commented on health-check/README.md
Since this is outside of `python/`, we need to adapt the Python checkstyle workflow yaml to cover it.

2024-12-11 13:01 UTC, agraul commented on health-check/src/uyuni_health_check/config.ini
Small question, can we use TOML instead? It's similar, but we've started using it more in other projects and it's widely used in the Python world these days.

2024-12-11 14:29 UTC, agraul commented on health-check/src/uyuni_health_check/config_loader.py
> +class ConfigLoader:
IMO there is no need for this class, the things it does are generally unrelated.

2024-12-11 14:29 UTC, agraul commented on health-check/src/uyuni_health_check/config_loader.py
> +        self.base_dir = os.path.dirname(os.path.abspath(__file__))
We probably want to have the config outside of the Python package in the future.

2025-01-21 08:44 UTC, m-czernek commented on health-check/src/uyuni_health_check/containers/exporter/Dockerfile
agreed, but resolving here in favor of fixing this in https://github.com/SUSE/spacewalk/issues/23179

2025-01-21 08:46 UTC, m-czernek commented on health-check/src/uyuni_health_check/containers/loki/Dockerfile
> +FROM docker.io/grafana/loki
Agreed, but resolving here in favor of fixing this in https://github.com/SUSE/spacewalk/issues/23179

2025-01-21 08:46 UTC, m-czernek commented on health-check/src/uyuni_health_check/containers/logcli/Dockerfile
> +COPY logcli-linux-amd64 /usr/bin/logcli
Agreed, but resolving here in favor of fixing this in https://github.com/SUSE/spacewalk/issues/23179

2025-01-21 08:46 UTC, m-czernek commented on health-check/src/uyuni_health_check/containers/grafana/Containerfile
> +FROM docker.io/grafana/grafana:latest
Agreed, but resolving here in favor of fixing this in https://github.com/SUSE/spacewalk/issues/23179

2025-01-22 13:03 UTC, m-czernek commented on health-check/src/uyuni_health_check/config_loader.py
> +class ConfigLoader:
Fixing in https://github.com/uyuni-project/uyuni/pull/9662, resolving here

2025-01-22 13:04 UTC, m-czernek commented on health-check/src/uyuni_health_check/config_loader.py
> +        self.base_dir = os.path.dirname(os.path.abspath(__file__))
Fixed in https://github.com/uyuni-project/uyuni/pull/9662, resolving here. We can have the `config.toml` wherever on the filesystem, the rest of the config is considered internal and stayed inside of the pkg (I'm open to changing this based on further suggestions of course)

2025-01-22 13:05 UTC, m-czernek commented on health-check/src/uyuni_health_check/config.ini
Fixed in https://github.com/uyuni-project/uyuni/pull/9662

2025-01-31 12:24 UTC, m-czernek commented
Remaining tasks:

- Apply formatting and linting: https://github.com/uyuni-project/uyuni/pull/9706
- Remove `uyuni` from the tool name/logs
- Move the code to the `python` dir (note: will have to tweak the formatting rules; this code is not compatible with Python 3.6 formatting)

2025-03-03 09:10 UTC, m-czernek commented on health-check/README.md
Moved to `python`

2025-03-27 09:50 UTC, meaksh commented
This PR should be ready to be merged now.

NOTE: the content of this PR has been already reviewed in the following PRs against `health-check-skeleton` branch, which is the source of this PR.

#9961
#9920
#9910
#9882
#9871
#9862
#9799
#9742
#9706
#9694
#9662

2025-03-28 12:31 UTC, m-czernek approved these changes
Leaving a few comments; overall LGTM!

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/exporters/supportconfig_exporter.py
> +            self.salt_configuration = self.read_salt_configuration()
non-blocking, but these checks should be included in the methods they are guarding, e.g. `read_salt_jobs` should have a guart statement `if not self.exists_salt_jobs_file():` etc.

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/config.py
> +def load_dockerfile_dir(dockerfile_dir: str) -> str:
non-blocking, we should unify these... `load` has a different meaning in this context.. Of course if this is accepted, we need to refactor all the method calls too.

Looking briefly at the code, we might be able to delete this method. We should double check whether there are methods not used now that we don't build containers.

```suggestion
def get_dockerfile_dir(dockerfile_dir: str) -> str:
```

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/containers/manager.py
> +def image_exists(image):
```suggestion
def image_exists(image: str) -> bool:
```

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/containers/manager.py
> +def network_exists(network):
```suggestion
def network_exists(network: str) -> bool:
```

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/containers/manager.py
> +def container_is_running(name):
```suggestion
def container_is_running(name: str) -> bool:
```

2025-03-28 12:31 UTC, m-czernek commented on python/health-check/src/health_check/exporters/supportconfig_exporter.py
> +    def __init__(self, supportconfig_path=None):
We require the path, then why do we set it to None...

```suggestion
    def __init__(self, supportconfig_path: str):
```

2025-03-28 13:01 UTC, meaksh commented on python/health-check/src/health_check/config/templates/promtail/promtail.yaml.j2
> +  filename: /tmp/positions.yaml
Hmm, indeed we don't need it anymore! :+1:

2025-03-28 13:06 UTC, meaksh commented on python/health-check/pyproject.toml
> +name = "health-check"
Hmmm, this one I'm not sure, as we use `health-check` as the name of the project, python directories, containers images names, etc.

I wouldn't  prefer to not redund the `mgr-` prefix in all those places but just use it for the CLI tool instead.

2025-03-28 13:34 UTC, meaksh commented on python/health-check/src/health_check/exporters/supportconfig_exporter.py
> +            self.salt_configuration = self.read_salt_configuration()
Fixed now

2025-03-28 14:07 UTC, m-czernek approved these changes

2025-04-02 11:18 UTC, deneb-alpha commented on containers/health-check-loki-image/health-check-loki-image.changes
> +- Initial version
The rest will be generated while tagging with tito
```suggestion
- Initial version
```

2025-04-02 11:18 UTC, deneb-alpha commented on containers/health-check-grafana-image/health-check-grafana-image.changes
> +- Initial version
The rest will be generated while tagging with tito
```suggestion
- Initial version
```

2025-04-02 11:20 UTC, deneb-alpha commented on python/health-check/MANIFEST.in
> +recursive-include src/health_check/containers *
Missing empty line at the end  of the file
```suggestion
include src/health_check/config.toml
recursive-include src/health_check/config *
recursive-include src/health_check/containers *

```

2025-04-02 11:22 UTC, deneb-alpha commented on python/health-check/README.md
> +A tool providing dashboard, metrics and logs from an Uyuni server supportconfig to visualise its health status.
If I'm not mistaken, we use en-US, so this should be with  Z (visualise -> visualize)
```suggestion
A tool providing dashboard, metrics and logs from an Uyuni Server supportconfig to visualize its health status.
```

2025-04-02 11:23 UTC, deneb-alpha commented on python/health-check/README.md
> +Execute the `start` phase of the tool as such:
```suggestion
This tool builds and deploys the necessary containers to scrape some metrics and logs from an Uyuni Server supportconfig directory.
Execute the `start` phase of the tool as such:
```

2025-04-02 11:24 UTC, deneb-alpha commented on python/health-check/mgr-health-check.changes
> +- Initial package
The rest will be generated while tagging with tito.

```suggestion
- Initial version
```

2025-04-02 11:25 UTC, deneb-alpha commented on python/health-check/mgr-health-check.spec
This new source also **requires a new entry in `rel-eng/packages`**

The file name must be: `mgr-health-check`

And  it's  content must be:

`5.1.0 python/health-check/`

2025-04-02 11:29 UTC, deneb-alpha commented on containers/health-check-grafana-image/Dockerfile
This new source also requires a new entry in `rel-eng/packages`

The file name must be: `health-check-grafana-image`

And it's content must be:

`5.1.0 containers/health-check-grafana-image`

2025-04-02 11:55 UTC, deneb-alpha requested changes
a few additional suggestions... but still not  done with all  the containers

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-loki-image/Dockerfile
> +ARG BASE=registry.suse.com/bci/bci-base:15.6
```suggestion
# SPDX-License-Identifier: MIT
#!BuildTag: uyuni/health-check-loki:latest

ARG BASE=registry.suse.com/bci/bci-base:15.7
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-promtail-image/Dockerfile
> +ARG BASE=registry.suse.com/bci/bci-base:15.6
```suggestion
# SPDX-License-Identifier: MIT
#!BuildTag: uyuni/health-check-loki:latest

ARG BASE=registry.suse.com/bci/bci-base:15.7
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-supportconfig-exporter-image/Dockerfile
> +ARG BASE=registry.suse.com/bci/bci-base:15.6
```suggestion
# SPDX-License-Identifier: MIT
#!BuildTag: uyuni/health-check-loki:latest

ARG BASE=registry.suse.com/bci/bci-base:15.7
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-loki-image/Dockerfile
This new source also requires a new entry in `rel-eng/packages`

The file name must be: `health-check-loki-image`

And it's content must be:

`5.1.0 containers/health-check-loki-image`

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-loki-image/Dockerfile
> +RUN zypper -n install loki
every RUN is a layer in the image. let's reduce them where we can...

```suggestion
RUN zypper --non-interactive ref && zypper --non-interactive up && \
         zypper --gpg-auto-import-keys --non-interactive install --auto-agree-with-licenses --force-resolution \
                      loki
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-promtail-image/Dockerfile
> +RUN zypper -n install promtail
every RUN is a layer in the image. let's reduce them where we can...

```suggestion
RUN zypper --non-interactive ref && zypper --non-interactive up && \
         zypper --gpg-auto-import-keys --non-interactive install --auto-agree-with-licenses --force-resolution \
                      promtail
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-supportconfig-exporter-image/Dockerfile
> +RUN zypper -n install python311-PyYAML
every RUN is a layer in the image. let's reduce them where we can...

```suggestion
RUN zypper --non-interactive ref && zypper --non-interactive up && \
         zypper --gpg-auto-import-keys --non-interactive install --auto-agree-with-licenses --force-resolution \
                       python311-PyYAML
```

2025-04-02 11:55 UTC, deneb-alpha commented on containers/health-check-supportconfig-exporter-image/Dockerfile
This new source also requires a new entry in `rel-eng/packages`

The file name must be: `health-check-supportconfig-exporter-image`

And it's content must be:

`5.1.0 containers/health-check-supportconfig-exporter-image`

2025-04-02 12:04 UTC, deneb-alpha requested changes

2025-04-02 12:04 UTC, deneb-alpha commented on containers/health-check-loki-image/Dockerfile
> +# Build Service required labels
harmonize with the other containers
```suggestion
# LABELs
ARG PRODUCT=Uyuni
ARG VENDOR="Uyuni project"
ARG URL="https://www.uyuni-project.org/"
ARG REFERENCE_PREFIX="registry.opensuse.org/uyuni"

# Build Service required labels
```

2025-04-02 12:04 UTC, deneb-alpha commented on containers/health-check-promtail-image/Dockerfile
> +# Build Service required labels
harmonize with the other containers
```suggestion
# LABELs
ARG PRODUCT=Uyuni
ARG VENDOR="Uyuni project"
ARG URL="https://www.uyuni-project.org/"
ARG REFERENCE_PREFIX="registry.opensuse.org/uyuni"

# Build Service required labels
```

2025-04-02 12:04 UTC, deneb-alpha commented on containers/health-check-supportconfig-exporter-image/Dockerfile
> +# Build Service required labels
harmonize with the other containers
```suggestion
# LABELs
ARG PRODUCT=Uyuni
ARG VENDOR="Uyuni project"
ARG URL="https://www.uyuni-project.org/"
ARG REFERENCE_PREFIX="registry.opensuse.org/uyuni"

# Build Service required labels
```

2025-04-02 12:04 UTC, deneb-alpha commented on containers/health-check-promtail-image/Dockerfile
This new source also requires a new entry in `rel-eng/packages`

The file name must be: `health-check-promtail-image`

And it's content must be:

`5.1.0 containers/health-check-promtail-image`

2025-04-02 12:44 UTC, deneb-alpha commented on python/health-check/pyproject.toml
> +description = "Show Uyuni server health metrics and logs"
```suggestion
description = "Show Uyuni Server health metrics and logs"
```

2025-04-02 12:44 UTC, deneb-alpha commented on python/health-check/src/health_check/config.toml
> +image = "registry.opensuse.org/systemsmanagement/uyuni/master/containers/uyuni/health-check-promtail:latest"
When we release it to stable, the container will be available from `image = "registry.opensuse.org/uyuni/`
```suggestion
image = "registry.opensuse.org/uyuni/health-check-promtail:latest"
```

2025-04-02 12:44 UTC, deneb-alpha commented on python/health-check/src/health_check/config.toml
> +image = "registry.opensuse.org/systemsmanagement/uyuni/master/containers/uyuni/health-check-supportconfig-exporter:latest"
When we release it to stable, the container will be available from `image = "registry.opensuse.org/uyuni/`
```suggestion
image = "registry.opensuse.org/uyuni/health-check-supportconfig-exporter:latest"
```

2025-04-02 12:44 UTC, deneb-alpha commented on python/health-check/src/health_check/config.toml
> +image = "registry.opensuse.org/systemsmanagement/uyuni/master/containers/uyuni/health-check-grafana:latest"
When we release it to stable, the container will be available from `image = "registry.opensuse.org/uyuni/`
```suggestion
image = "registry.opensuse.org/uyuni/health-check-grafana:latest"
```

2025-04-02 12:44 UTC, deneb-alpha commented on python/health-check/src/health_check/config.toml
When the  images will be released in the next Uyuni release,  the containers will all be available directly from `registry.opensuse.org/uyuni/`

But until we don't have a release, I don't know if you prefer to keep the image reference pointing to Master

2025-04-02 12:51 UTC, meaksh commented on python/health-check/src/health_check/config.toml
I would say to keep the current config for the containers image sources to `systemsmanagement/uyuni/master/`, until we prepare the next Uyuni submission.

2025-04-03 07:13 UTC, deneb-alpha requested changes
There's also a missing service `to be added for each container source` that is needed for avoiding the invalid reference format build error.

Please, add a  new file called `_service` with the following content:

~~~
<services>
  <service mode="buildtime" name="kiwi_metainfo_helper"/>
  <service mode="buildtime" name="docker_label_helper"/>
</services>
~~~

2025-04-03 07:13 UTC, deneb-alpha commented on containers/health-check-grafana-image/Dockerfile
There's also a missing service that is needed for avoiding the invalid reference format  build error.

Please, add a  new file called `_service` with the following content:

~~~
<services>
  <service mode="buildtime" name="kiwi_metainfo_helper"/>
  <service mode="buildtime" name="docker_label_helper"/>
</services>
~~~

2025-04-03 07:13 UTC, deneb-alpha commented on containers/health-check-loki-image/Dockerfile
There's also a missing service that is needed for avoiding the invalid reference format  build error.

Please, add a  new file called `_service` with the following content:

~~~
<services>
  <service mode="buildtime" name="kiwi_metainfo_helper"/>
  <service mode="buildtime" name="docker_label_helper"/>
</services>
~~~

2025-04-03 07:13 UTC, deneb-alpha commented on containers/health-check-promtail-image/Dockerfile
There's also a missing service that is needed for avoiding the invalid reference format  build error.

Please, add a  new file called `_service` with the following content:

~~~
<services>
  <service mode="buildtime" name="kiwi_metainfo_helper"/>
  <service mode="buildtime" name="docker_label_helper"/>
</services>
~~~

2025-04-03 07:13 UTC, deneb-alpha commented on containers/health-check-supportconfig-exporter-image/Dockerfile
There's also a missing service that is needed for avoiding the invalid reference format  build error.

Please, add a  new file called `_service` with the following content:

~~~
<services>
  <service mode="buildtime" name="kiwi_metainfo_helper"/>
  <service mode="buildtime" name="docker_label_helper"/>
</services>
~~~

2025-04-03 09:24 UTC, meaksh commented on containers/health-check-grafana-image/Dockerfile
done

2025-04-03 09:24 UTC, meaksh commented on containers/health-check-promtail-image/Dockerfile
done

2025-04-03 09:24 UTC, meaksh commented on containers/health-check-supportconfig-exporter-image/Dockerfile
done

2025-04-03 09:24 UTC, meaksh commented on containers/health-check-loki-image/Dockerfile
done

2025-04-03 12:33 UTC, agraul commented on python/health-check/src/health_check/__init__.py
> +__version__ = "5.1.0"
How will this be updated in the future?

2025-04-07 10:01 UTC, meaksh commented on python/health-check/src/health_check/__init__.py
> +__version__ = "5.1.0"
Ideally this should be upgraded automatically when running `tito tag`, in the same way the version in the spec is updated.

For that, we would need extend the current tagger used for `mgr-health-check` package via `rel-eng/custom/custom.py`, as it is done for other packages.

I'm having a look to this at the moment.

2025-04-07 10:09 UTC, meaksh commented
It has been decided after some discussion to not integrate yet the Health Check into the main "Uyuni" repository, as it is not yet meeting the requirements from RelEngs. Packages inside this repo are expected to be part of the products (both Uyuni and MLM), to be released as part of the product and expected to be successfully build at OBS/IBS.

Currently, this initial iteration of the health check is targetted for supporters and developers, and not going to be included yet as part of product channels.

For now, this is a tool that works for every version of Uyuni and MLM, which is going to be delived out of the product channels.

We just moved the content of this PR to the new created GitHub repository: https://github.com/uyuni-project/health-check, so I'm closing this PR for now and will continue efforts on this separated repo.

2025-04-07 10:09 UTC, closed without merging