Add reboot in cleanup after package removal before file removal
uyuni-project/uyuni pull request #9384
Opened 2024-10-17 15:46 UTC by ktsamis

## What does this PR change?

port of https://github.com/SUSE/spacewalk/pull/25556/

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: only internal and user invisible changes

- [x] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: already covered

- [x] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/24035
Port(s): 

master: current PR
5.0: https://github.com/SUSE/spacewalk/pull/25556/
4.3: 

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [x] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2024-10-17 16:25 UTC, vzhestkov approved these changes
LGTM. I hope we can improve the bootstrap state to avoid such corner cases with file cleanups, but I haven't yet tried to fix it.

2024-10-18 08:17 UTC, vzhestkov requested changes
I think we can improve the way of cleanup instead of rebooting in each step. I just checked the bootstrap state and it's checking for the case of presence the minion config directory, but as you remember while testing after reboot we saw empty config directory even if it was deleted explicitly before reboot.

So suggestion is the following:
- Do not delete `/etc/venv-salt-minion` and `/etc/salt` completely
- Delete just the following from the config dir:
    ```
    grains
    minion_id
    minion.d/* (except 00-venv.conf)
    pki/minion/*
    ```
    `minion.d/* (except 00-venv.conf)` can be done with `find /etc/venv-salt-minion/minion.d/ -type f ! -name '00-venv.conf' -delete`

`00-venv.conf` is only relevant for the salt bundle, for classic salt package it could be `transactional_update.conf`, but not sure if it's used in the testsuite, but it shouldn't be a problem to not delete it.

2024-11-13 11:30 UTC, Bischoff approved these changes
don't forget to squash the commits

2024-11-13 13:15 UTC, vzhestkov approved these changes
LGTM. Thanks for rendering all the suggestions to the correct form :-D :+1:

2024-11-13 16:23 UTC, NamelessOne91 approved these changes

2024-11-29 10:36 UTC, merged