Fake packages checks fixes
uyuni-project/uyuni pull request #9391
Opened 2024-10-21 12:23 UTC by NamelessOne91

## What does this PR change?

Fixes some broken testsuite checks on dummy RPM packages

1) `virgo-dummy` exists but is displayed in the 2nd page of results, as the testsuite browser only displays up to 25 packages in one page and it is at number 26 and 27 

2) the checksum for `andromeda-dummy` is different (expected ?)

## GUI diff

No difference.

- [ ] **DONE**

## Documentation

- No documentation needed: only internal and user invisible changes

- [ ] **DONE**

## Test coverage

- Cucumber tests were modified

- [ ] **DONE**

## Links

Port(s) 

- 4.3:
- 5.0:

- [ ] **DONE**

## Changelogs

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

2024-10-21 12:51 UTC, srbarrios approved these changes

2024-10-22 08:49 UTC, Bischoff requested changes
let's rather fix on OBS

2024-10-22 11:15 UTC, srbarrios approved these changes

2024-10-22 13:56 UTC, Bischoff approved these changes

2024-10-22 19:22 UTC, maximenoel8 approved these changes

2024-10-23 08:01 UTC, merged