Force the generation of bootstrap repositories in CT
uyuni-project/uyuni pull request #9535
Opened 2024-12-03 15:47 UTC by srbarrios

## What does this PR change?

**add description**

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2025-01-07 13:37 UTC, szachovy requested changes

2025-01-07 13:37 UTC, szachovy commented on testsuite/features/init_clients/sle_minion.feature
> +  Scenario: Clean up sumaform leftovers on SLES minion
Why exactly are we doing this cleanups now, is there a reason behind it considering that we have been living without it for years?

2025-01-07 13:37 UTC, szachovy commented on testsuite/features/step_definitions/command_steps.rb
> +  get_target('server').run('mgr-create-bootstrap-repo --auto --force --with-custom-channels', check_errors: false, verbose: true)
```
  def wait_while_process_running(process)
    repeat_until_timeout(report_result: true) do
      result, code = run("pgrep -x #{process} >/dev/null", check_errors: false)
      return [result, code] if code.nonzero?

      sleep 2
      result
    end
  end
```

It seems to me that it starts waiting -> ends waiting -> runs `mgr-create-bootstrap-repo` command as I do not see any parallel mechanisms that runs next commands without waiting for return code.
Can you provide me the screenshot that these 2 processes are present simultaneously in any time for at max 2 seconds?

2025-01-07 13:45 UTC, srbarrios commented on testsuite/features/step_definitions/command_steps.rb
> +  get_target('server').run('mgr-create-bootstrap-repo --auto --force --with-custom-channels', check_errors: false, verbose: true)
mgr-create-bootstrap-repo it gonna be automatically triggered by the server in a periodical manner, this just tries to prevent the colision, still it could happen that when we run our second line, the server tries to also trigger it automatically.

We usually don't need to care about bootstrap creation because it's triggered periodically by the server, but... the default behavior don't include custom channels, which is our case here.

Hard to give you a probe of this :)

2025-01-07 14:00 UTC, szachovy commented on testsuite/features/step_definitions/command_steps.rb
> +  get_target('server').run('mgr-create-bootstrap-repo --auto --force --with-custom-channels', check_errors: false, verbose: true)
Okay, I understand. Closing

2025-01-08 09:56 UTC, srbarrios commented on testsuite/features/init_clients/sle_minion.feature
> +  Scenario: Clean up sumaform leftovers on SLES minion
I edited the description to clarify it.

2025-01-08 11:08 UTC, szachovy commented on testsuite/features/init_clients/sle_minion.feature
> +  Scenario: Clean up sumaform leftovers on SLES minion
Ok, closing

2025-01-08 11:08 UTC, szachovy approved these changes

2025-01-13 09:23 UTC, merged

2025-01-13 11:30 UTC, srbarrios commented
Note:
Review which salt-bundle package it gonna install, because it might use the one from the boostrap repository which is in fact the released package, instead of the package from development coming in the injected repository through sumaform.