Hibernate queries refactoring
uyuni-project/uyuni pull request #9588
Opened 2024-12-19 16:56 UTC by mbussolotto

## What does this PR change?

**add description**

## GUI diff

No difference.

Before:

After:

- [ ] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [ ] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [ ] **DONE**

## Links

Issue(s): #
Port(s): # **add downstream PR(s), if any**

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "javascript_lint"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

2025-01-15 12:26 UTC, mcalmer requested changes

2025-01-15 12:26 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
> +        getSession().createNativeQuery("DROP TABLE suseSCCSubscription CASCADE");
This is wrong. We want to drop all data, but not the table.
```suggestion
        getSession().createNativeQuery("DELETE FROM suseSCCSubscription");
```

2025-01-15 12:35 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
> +        sqlQuery.append(" ORDER BY name ASC, version ASC, release ASC, arch_type_id ASC");
I think something in this query is wrong. 
I get:

```
SELECT * FROM suseProducts
 WHERE LOWER(name) = :name
   AND LOWER(version) = :version
   AND (release IS NULL OR LOWER(release) = :release) AND LOWER(release) = :release
   AND arch_type_id = :arch
 ORDER BY name ASC, version ASC, release ASC, arch_type_id ASC
```
with release = ""

2025-01-15 14:03 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
> +        sqlQuery.append(" ORDER BY name ASC, version ASC, release ASC, arch_type_id ASC");
fixed

2025-01-21 13:50 UTC, cbosdo reviewed
I didn't check every query change, but it seems good to me. I left some cosmetic suggestions.

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
> +//            AvailableChannelsView.class,
Could you avoid a giant diff hunk just for a commented line? And leaving commented code is a bad habit: should it be kept and fixed or removed?

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/BaseDomainHelper.java
> +public abstract class BaseDomainHelper implements Serializable {
Did you check the sonarcloud reports about Serializable? This can grow big since all its fields need to be serializable too.

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
> +                LEFT JOIN rhnChannelCloned c_1_ ON c.id = c_1_.id
can't there be a better name than `c_1_` ?

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/channel/ChannelFamilyFactory.java
> +            query.setParameter("org",   -1);
```suggestion
            query.setParameter("org", -1);
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/channel/ChannelFamilyFactory.java
> +            query.setParameter("org",   -1);
```suggestion
            query.setParameter("org", -1);
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/channel/ChannelFamilyFactory.java
> +                getSession().createNativeQuery(sql, ChannelFamily.class);
```suggestion
        TypedQuery<ChannelFamily> query = getSession().createNativeQuery(sql, ChannelFamily.class);
```
Doesn't it fit in 120 characters?

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/credentials/test/CredentialsTest.java
> +                        "select password from suseCredentials where username = 'admin';")
doesn't that fit under the 120 characters in one line?

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
> +                                      SELECT * from suseProductExtension""", SUSEProductExtension.class)
```suggestion
        return getSession().createNativeQuery(
                                      "SELECT * from suseProductExtension", SUSEProductExtension.class)
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
> +                                      """, SUSEProduct.class)
```suggestion
        return getSession().createNativeQuery("SELECT * from suseProducts",
                                      SUSEProduct.class)
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
> +                                      """, SCCSubscription.class)
```suggestion
        return getSession().createNativeQuery("SELECT * from suseSCCSubscription",
                                      SCCSubscription.class)
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
> +                                      """, SCCOrderItem.class)
```suggestion
        return getSession().createNativeQuery("SELECT * from suseSCCOrderItem",
                                      SCCOrderItem.class)
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
> +                                      """, SCCRepositoryAuth.class)
```suggestion
        return getSession().createNativeQuery("SELECT * from suseSCCRepositoryAuth",
                                      SCCRepositoryAuth.class)
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
> +                "CustomDataValue.findByServerAndKey")
```suggestion
                return (CustomDataValue) session.getNamedQuery("CustomDataValue.findByServerAndKey")
```
Getting the query name with the function call is likely to be less than 120, and the alignment is confusing.

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
> +        """;
```suggestion
        String sql = "SELECT *, 0 as clazz_ FROM rhnServer s";
```

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstance.lookupGuestBySid")
Probably the line break before this line could be removed or the alignment fixed

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceType.findByLabel")
here too

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceType.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceType.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +            "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +            "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +            "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/VirtualInstanceFactory.java
> +                "VirtualInstanceState.findByLabel")
and here

2025-01-21 13:50 UTC, cbosdo commented on java/code/src/com/redhat/rhn/domain/server/virtualhostmanager/VirtualHostManagerFactory.java
> +                                      """, VirtualHostManager.class)
```suggestion
        return HibernateFactory.getSession().createNativeQuery(
                                      "SELECT * from suseVirtualHostManager",
                                      VirtualHostManager.class)
```

2025-01-21 14:47 UTC, mbussolotto commented on java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
> +//            AvailableChannelsView.class,
I can remove the comment, but the giant diff would remain since I order them in alphabetic order: I'll add a comment to be sure next class would be added in this way.

2025-01-22 14:04 UTC, mbussolotto commented on java/code/src/com/redhat/rhn/domain/BaseDomainHelper.java
> +public abstract class BaseDomainHelper implements Serializable {
I fixed them, (just one with `pillar` is left, but it would require lots of changes...I'd like to monitor it and be sure it's really required)

2025-01-22 14:47 UTC, cbosdo submitted a review, later dismissed
LGTM

2025-01-22 14:47 UTC, cbosdo commented on java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
> +            // do not add class at the endi, but keep the alphabetical order
```suggestion
            // do not add class at the end, but keep the alphabetical order
```

2025-01-22 15:05 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                                      """, MinionServer.class)
we had problems with "DISTINCT" in the query. Maybe we can test this query if it really report every minion only 1 time?

2025-01-22 15:06 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                    .uniqueResult());
same as above

2025-01-22 15:12 UTC, mcalmer commented on java/code/src/com/redhat/rhn/taskomatic/TaskoFactory.java
> +                        """;
I think the indentation can be improved here

2025-01-22 16:06 UTC, mbussolotto commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                                      """, MinionServer.class)
do you mean:
- remove "DISTINCT" and check if unit test are still ok or
- add new unit tests for these particular queries
?

2025-01-22 16:19 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                                      """, MinionServer.class)
Well, no. The queston is: does this "DISTINCT" here what we want?
Yesterday I found out that it was not doing what I expected.

2025-01-22 16:48 UTC, mbussolotto commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                                      """, MinionServer.class)
well, I tried to run the queries (with and without) distinct in our large environment: the result was the same. Morever we have in `suseMinionInfo`:
```
    server_id             NUMERIC NOT NULL
                              CONSTRAINT suse_minion_info_sid_fk
                                  REFERENCES rhnServer (id)
                                  ON DELETE CASCADE,
``` 
and
```
ALTER TABLE suseMinionInfo
 ADD CONSTRAINT rhn_minion_info_sid_uq UNIQUE (server_id);
```
So I think we cannot have duplicated here and distinct is useless. What do you think?

2025-01-22 20:07 UTC, mcalmer commented on java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
> +                                      """, MinionServer.class)
Sounds good

2025-01-23 09:47 UTC, mcalmer approved these changes

2025-01-23 09:48 UTC, mcalmer commented
@mbussolotto you should look into the acceptance tests. Some fail and I do not know if this has something to do with your code changes or not.

2025-01-23 10:23 UTC, cbosdo commented
> @mbussolotto you should look into the acceptance tests. Some fail and I do not know if this has something to do with your code changes or not.

All acceptance tests are currently broken due to the setup PR I merged yesterday.

2025-01-31 08:15 UTC, merged